### ISSUE TITLE
Allow cloning of documents

### ISSUE THREAD

**Issue by tautrimas** [ongr-io/ElasticsearchBundle#107]
```php
$documentCopy = clone $document;
```

Above should create persistable document with ID being empty. This is Doctrine behaviour when one can easily clone entities that have been fetched from DB.

**Comment by martiis** [comment]
This could be implemented in DocumentTrait

**Comment by saimaz** [comment]
IMO its not good place to put magic methods in the traits.

**Comment by tautrimas** [comment]
maybe we can add it to proxy class as Doctrine does?

**Comment by martiis** [comment]
Yeah, but it would only work on proxies.

**Comment by saimaz** [comment]
+1 @tautrimas User document is a user document, we have no right to interfere between it.

**Comment by martiis** [comment]
After #80 :)

**Comment by mvar** [comment]
@tautrimas do you remember why this feature was needed?

I'm going to remove it as I see no point to leave it.

Also statement "This is Doctrine behaviour" does not look correct. Doctrine never resets your ID. It only overwrites it with generated value if you have added `@GeneratedValue` annotation.

**Comment by tautrimas** [comment]
I don't remember (: There are times when one needs a copy for storing the object elsewhere or a duplication feature that is sometimes needed.

When I think of it, recursive cloning would be needed anyways, so I would personaly serialize and deserialize needed document and unset the `_id`.

Maybe this was an improvement request.
