### ISSUE TITLE
Receiving Bad Request response after trying to commit without any changes.

### ISSUE THREAD

**Issue by GrandLTU** [ongr-io/ElasticsearchBundle#110]
IF no documents were persisted after invoking $manager->commit() app crashes with Bad Request response from es.

**Comment by martiis** [comment]
@trylika @saimaz to throw or not to throw?

**Comment by trylika** [comment]
@martiis throw, but error should be more informative, other that bad request.
Doctrine throws specific error if transaction wasn't made.

**Comment by saimaz** [comment]
https://github.com/ongr-io/ElasticsearchBundle/issues/356
