### ISSUE TITLE
abstract filter is only used in post filter

### ISSUE THREAD

**Issue by saimaz** [ongr-io/ElasticsearchBundle#115]
Before refactor in all filters abstract filter was used, now there is only post filter who left it. Maybe we should consider to merge contents from abstraction to post filter.

**Comment by martiis** [comment]
[FilteredQuery](https://github.com/ongr-io/ElasticsearchBundle/blob/7ed7ffc6f97477f7ecb6e30b4d7aad37ac1dfa0b/DSL/Query/FilteredQuery.php) also.

**Comment by saimaz** [comment]
@martiis is this issue is still relevant after your endpoint builder?

**Comment by saimaz** [comment]
There is no abstract filter any more
