### ISSUE TITLE
create search templates

### ISSUE THREAD

**Issue by saimaz** [ongr-io/ElasticsearchBundle#118]
Define filters and queries as services. This could allow as to create search templates for easier query building.

**Comment by martiis** [comment]
How about queries container service?

**Comment by saimaz** [comment]
Sounds also promising.

**Comment by laurusCN** [comment]
template is a very important feature.

**Comment by saimaz** [comment]
Maybe you have any suggestions? Any chance you can do a pull request for this issue?

**Comment by saimaz** [comment]
Closing it for now. After 2 years of thinking, it doesn't appear to a real use case.
