### ISSUE TITLE
ElasticsearchTestCase should be AbstractElasticsearchTestCase or not an abstract class

### ISSUE THREAD

**Issue by saimaz** [ongr-io/ElasticsearchBundle#121]
We are braking naming conventions calling abstract class without Abstract prefix. Lets investigate if it could be not an abstract class.

**Comment by tautrimas** [comment]
And there we go with [`WebTestCase`](https://github.com/symfony/FrameworkBundle/blob/master/Test/WebTestCase.php#L21) ):

**Comment by saimaz** [comment]
Well, its old class :). But it should be fine with `WebTestCase`, the source is in the symfony, checker should not conflict with it.

**Comment by tautrimas** [comment]
This is a valid issue, and should be resolved with BC and `@deprecated` tags

**Comment by martiis** [comment]
Closed by https://github.com/ongr-io/ElasticsearchBundle/pull/163
