### ISSUE TITLE
Implement UnitOfWork

### ISSUE THREAD

**Issue by martiis** [ongr-io/ElasticsearchBundle#125]
When documents are persisted in manager they should be put in UnitOfWork instance. It should be responsible for tracking changes to objects during an "object-level" transaction and for writing out changes to the client in the correct order.

[Doctrine example](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/UnitOfWork.php)

**Comment by martiis** [comment]
This should also solve https://github.com/ongr-io/ElasticsearchBundle/issues/110

**Comment by saimaz** [comment]
Lets discuss if it would make sense to change behaviour by UnitOfWork example.
