### ISSUE TITLE
getter method is required even for boolean property which has is[Property]

### ISSUE THREAD

**Issue by trylika** [ongr-io/ElasticsearchBundle#132]
got this error on Document, which has "active" property and had isActive method:

exception 'LogicException' with message 'Getter for property "active" can not be found.' in /var/www/OXIDConnectorBundle/vendor/ongr/elasticsearch-bundle/Mapping/MetadataCollector.php:400

**Comment by martiis** [comment]
This shouldn't be an issue in next release with document proxies.

**Comment by trylika** [comment]
i think this issue is duplicate for #58

**Comment by martiis** [comment]
With @saimaz we discussed that prefix `is` won't be implemented (for now) because it breaks the consistency, and would require an extra check if type is bool.

**Comment by saimaz** [comment]
Well this is very debatable topic for is it worth to have or not. Seems like these Hassers/Issers is very useful as an addition.

**Comment by saimaz** [comment]
We cant use only hassers/issers withut get and set. These methods is an extension. IMO Getter still should exist.

**Comment by saimaz** [comment]
From now on we do not care if user created getters, setters, the properties are public or private, its up to the user how to handle access to the documents.
