### ISSUE TITLE
Method offsetGet() in file AbstractResultsIterator gets notice about undefined index.

### ISSUE THREAD

**Issue by gyKa** [ongr-io/ElasticsearchBundle#136]
Method should handle a case, when needed document doesn't exists.

**Comment by martiis** [comment]
Iterator should return undefined index if you try to access it like array. To check if document exists offsetExists comes in which is fired when `isset()` is used.

**Comment by gyKa** [comment]
I've just found out, that old releases (e.g. v0.2.0) have this bug only. Thanks :)
