### ISSUE TITLE
Reflection Exception when specifying a document_dir and using an ES\Object

### ISSUE THREAD

**Issue by sabinebaer** [ongr-io/ElasticsearchBundle#139]
I get a reflection exception when I try to retrieve a document which has (amongst others) a property declared as follows:
@ES\Property(name="documentPart", type="object", objectName="MyNameDocumentsBundle:DocumentPart", multiple=true)

The document_dir in the config is set to: MyPath1/MyPath2

Exception:
ReflectionException: Class MyName\Bundle\MyBundle\MyPath1/MyPath2\DocumentPart does not exist

This seems to be related to https://github.com/ongr-io/ElasticsearchBundle/pull/102 - it seems to work if I add the str_replace which was added in this pull request to getNamespace(...) in MetadataCollector.php.

Is this a bug or am I doing something wrong?

**Comment by martiis** [comment]
Hi, I just double checked that and Yes it is a bug. In dev-master MetadataCollector has some major changes and this issue was (somehow) undetected. We'll fix it ASAP and try to release it in upcoming days or weeks. Thanks.
