### ISSUE TITLE
Semantic exception should be thrown when document is not found

### ISSUE THREAD

**Issue by tautrimas** [ongr-io/ElasticsearchBundle#160]
When `$repository->find('bad_id');` is executed, `Missing404Exception` is thrown. It should throw custom exception from `ONGR\ElasticsearchBundle` namespace.

**Comment by martiis** [comment]
What about keeping ESB as more like a bridge to symfony?

**Comment by saimaz** [comment]
I completely agree with @martiis. Meanwhile @martiis implemented https://github.com/ongr-io/ElasticsearchBundle/pull/214 which looks quite good solution when document is not found. Later I think we could extend this to the configuration where user can select what response he wants, `null` or an `exception`. But thats later. For now I propose to close this issue.

**Comment by saimaz** [comment]
Solved in #405 

Now it returns null.
