### ISSUE TITLE
Helper method findOrNull needed

### ISSUE THREAD

**Issue by tautrimas** [ongr-io/ElasticsearchBundle#161]
When `$repository->find('bad_id');` is executed, exception is thrown. Very good, but helper method should exist, that returns `null`, when document is not found.

I propose `findOrNull` name. Another options: 1. add optional argument 2. provide static helper for wrapping this method.

**Comment by martiis** [comment]
How about `$repository->find($id, $flag)` Flag would be a constant that would tell to throw exception or not.

**Comment by tautrimas** [comment]
@martiis already implemented the parameter solution. @saimaz, @mindaugasbarysas what are your opinions?

**Comment by martiis** [comment]
easy peasy :)

**Comment by mindaugasbarysas** [comment]
Just a thought: maybe both, where `findOrNull` would be a wrapper for `find($id, RETURN_NULL)`?

**Comment by tautrimas** [comment]
I would advise against multiple solutions. It's either this or that, in my opinion.

**Comment by mindaugasbarysas** [comment]
In that case I would probably suggest using a flag specifying desired mode of operation.

**Comment by saimaz** [comment]
We discussed this case with @martiis and seems like the best option would be to return `null` when document is not found instead of exception.

**Comment by tautrimas** [comment]
@martiis implemented flag support. `null` will break bundles. Is there a migration plan or new function will be added?

**Comment by martiis** [comment]
The softest migration I think now is to add deprecated null and exception flags, by default exception. Then you change flags to null, after that we remove flags parameter but keep constants for BC (removed parameter wont break either). Lastly you remove the flags and then we, but this IMO would take long.

Second we just change right now on dev-master. Then you could change on your master branches (with locally pulled ESB dev-master) and everyone makes a release :)

**Comment by tautrimas** [comment]
Would it be possible to checkout all projects, do a change to `null` and see how much breakage there would be?

I suspect that sometimes there will be untested functionality where the program should just crash because of unfound document. Now, it would crash with `non-object` PHP error.

Could you discuss this investigation with team, @martiis?

**Comment by saimaz** [comment]
Lets change it everywhere at once, I dont think so that there will be so much breaks. Comparing `exception` and `null` return the `null` way is much more reliable.
