### ISSUE TITLE
Delete mapping type

### ISSUE THREAD

**Issue by chyzas** [ongr-io/ElasticsearchBundle#170]
Needs an ability to delete a mapping (type) along with its data using console commands.

**Comment by martiis** [comment]
We could add these:
 - `es:type:create`
 - `es:type:update` (already have)
 - `es:type:drop`

But when we implement these I think we should not put mapping with `es:index:create`. What do you think @saimaz ?

**Comment by saimaz** [comment]
To insert mapping should be possible even at the first time with the update command, and for the create command could be introduced additional option to not create mapping but default should be set to create it.
