### ISSUE TITLE
get first result element after execute method

### ISSUE THREAD

**Issue by saimaz** [ongr-io/ElasticsearchBundle#172]
Would be great to have ability to get first element of query. First option is to add additional flag to execute f.g. `RESULT_ARRAY_FIRST`

However maybe its better to integrate additional method in the `Iterator` class.

```
$firstResult = $repository->execute($search)->first();
```

**Comment by martiis** [comment]
`first()` looks better :)

**Comment by saimaz** [comment]
But it will work only on iterators

**Comment by martiis** [comment]
Actually to get first of iterator would be simple as `$first = reset($repository->execute($search))` so maybe it isn't so useful, but `execute()` already has flags and adding an extra one wouldn't hurt :)

**Comment by saimaz** [comment]
Thanks for PR, but its too quick and IMO to mix flags with different behaviour is not very good. Even if the name will be different, this will still be a code duplication in the switch cycle. Probably the best way for this functionality is just to allow it on the iterators and thats it.
