### ISSUE TITLE
Parent-Child relationship

### ISSUE THREAD

**Issue by juliensantos87** [ongr-io/ElasticsearchBundle#187]
How to Query, Filter or Aggregate with Parent-Child relationship?
Do we have to create new DSL objects? 

Thanks

**Comment by electrobits** [comment]
That's exactly the problem I just faced.

```
{
    "query": {
        "has_parent": {
            "type": "database",
            "query": {
                "match": {
                    "id": 1
                }
            }
        }
    }
}
```

How to query something like above?

Thanks

**Comment by saimaz** [comment]
First off all you need to have right mapping to do something with parent/child. In the document annotation you need to define relation to the parent: https://github.com/ongr-io/ElasticsearchBundle/blob/6f6b225867b64bda9e88cb165a22bd9e8b4eb908/Annotation/Document.php#L35

Currently we do not have has_parent and has_children queries support. I created an issue, so soon it will be implemented. https://github.com/ongr-io/ElasticsearchBundle/issues/188

**Comment by juliensantos87** [comment]
@saimaz Thanks, could you also plan children aggregation ?

**Comment by saimaz** [comment]
@juliensantos87 thanks for notice, sure we will add children aggregation also.
