### ISSUE TITLE
Probably wrong exception thrown

### ISSUE THREAD

**Issue by lauriis2** [ongr-io/ElasticsearchBundle#206]
https://github.com/ongr-io/ElasticsearchBundle/blob/d0ded7c1cb8e40f3d34b0e89223242bed484c2da/Document/DocumentTrait.php#L200

Steps to reproduce:
Exception was thrown when trying to access this getter in dynamically generated ES Document (it was not retrieved from ES)

\UnderflowException is thrown, which states that "Exception thrown when performing an invalid operation on an empty container"
This is rather misleading because container (ES Document?) is not empty

**Comment by saimaz** [comment]
Did you set highlight to the document?

**Comment by lauriis2** [comment]
No, highlight was not set. And the exception should be thrown as it is now, but you could probably throw another exception, more self-descriptive one.

**Comment by saimaz** [comment]
IMO `UnderflowException` is very well selected and describes exactly what is wrong here. @lauriis2  if you do not agree, please suggest better exception and reopen issue.
