### ISSUE TITLE
field value evaluator, to get nested values from document

### ISSUE THREAD

**Issue by trylika** [ongr-io/ElasticsearchBundle#220]
There is need for functionality, to get any nested value from `Document`, by passing string depicting value requested. I.e.

`personDocument.getValue('work.address.street')`

would get from Person Document, it's work object's street name.

**Comment by martiis** [comment]
Try using http://symfony.com/doc/current/components/property_access/introduction.html#reading-from-arrays

**Comment by saimaz** [comment]
Would be nice inject `PropertyAccess` in the proxy class.

**Comment by saimaz** [comment]
I think that `getValue` method is not the best choice, because there is sligthly high chance that user will create a document with `$value` property, and then we will override his getter...

**Comment by lmikelionis** [comment]
I would call that method: getValueFromField()
