### ISSUE TITLE
Can Repository::getTypes method be public?

### ISSUE THREAD

**Issue by tautrimas** [ongr-io/ElasticsearchBundle#234]
Can [Repository::getTypes](https://github.com/ongr-io/ElasticsearchBundle/blob/591c45b357d4c1f25f3b7dacc2916006012f3914/ORM/Repository.php#L74) be public?

We need to perform custom bulk query and we need to read repositories' type name from the `Repository` object we have injected.

**Comment by saimaz** [comment]
Lets change this method to public.
