### ISSUE TITLE
There is no geo location filter

### ISSUE THREAD

**Issue by trylika** [ongr-io/ElasticsearchBundle#238]
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-geo-distance-filter.html

**Comment by chyzas** [comment]
There is a geo distance filter: https://github.com/ongr-io/ElasticsearchBundle/blob/master/DSL/Filter/GeoDistanceFilter.php

**Comment by trylika** [comment]
sorry about that, had an older version
