### ISSUE TITLE
Function Score generates double array

### ISSUE THREAD

**Issue by trylika** [ongr-io/ElasticsearchBundle#242]
when passing array of functions to FunctionScoreQuery, it generates final query with double array ( https://github.com/ongr-io/ElasticsearchBundle/blob/master/DSL/Query/FunctionScoreQuery.php#L66 ).

Generated query:```
"function_score": {
  "query": {
    "match_all": {}
  },
  "functions": [
    [
      {
        "boost_factor": 2,
        "filter": {
          "term": {
            "provider": "faker",
            "_cache": false
          }
        }
      }
    ]
  ],
  "score_mode": "sum",
  "boost_mode": "sum"
}```

passed arguments:
```$function = [
[
            'boost_factor' => $this->boost,
            'filter' => [
                'term' => [
                    $this->field => $value,
                    '_cache' => false,
                ],
            ],
        ],
];

new FunctionScoreQuery(new MatchAllQuery(), $functions);```

**Comment by saimaz** [comment]
Its already solved in #247
