### ISSUE TITLE
tearDown should not drop indexes

### ISSUE THREAD

**Issue by tautrimas** [ongr-io/ElasticsearchBundle#255]
It's not common to drop indexes after tests. It's not necessary. Index dropping is enough in the beginning of the test.

https://github.com/ongr-io/ElasticsearchBundle/blob/ac6a297f1e264149638d1b14ce6a60709e7761a1/Test/AbstractElasticsearchTestCase.php#L175

**Comment by saimaz** [comment]
For those projects which have more than one environment to test this delete operation is useful. We only missing one option, where test would create unique index name and will remember which one exactly to delete. 

p.s. we already have timestampable suffixes, but `AbstractElasticsearchTestCase` can't store the name until test ends.

**Comment by saimaz** [comment]
To test dsl and other read operations we must keep index with same data. It would improve performance a lot for tests.
