### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by mcrumm** [ongr-io/ElasticsearchBundle#284]
Any chance of getting a tagged release for all the updates on the master branch?  I'd like to use the new features, specifically the Geo filters, but I don't want to rely on using master, which is obviously under heavy development.

**Comment by martiis** [comment]
We are expecting to make a new release next week. There shouldn't be any major BC's during that time :)

**Comment by mcrumm** [comment]
Awesome!  I look forward to it.
