### ISSUE TITLE
HHVM incompatibility

### ISSUE THREAD

**Issue by Im0rtality** [ongr-io/ElasticsearchBundle#301]
https://github.com/ongr-io/ElasticsearchBundle/blob/master/Document/AbstractDocument.php#L91

Consider having this class:
```php
class ProductDocument extends AbstractDocument {
    private $foo;
    protected $bar;
    public $baz;

   // public getters and setters - as usual
}
```

When executing `AbstractDocument::__set()` parent class is only supposed to see `$this->baz` due to scopes. However due to PHP quirks following code works. However HHVM is more strict and does not allows such hacks (it crashes).

**Comment by saimaz** [comment]
The solution was simply remove that setter.
