### ISSUE TITLE
[mapping] Enabled setting in annotation is missing (workaround available)

### ISSUE THREAD

**Issue by tautrimas** [ongr-io/ElasticsearchBundle#303]
See: http://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-object-type.html#_enabled_3

Is it possible to add `enabled: false` to a property?

**Comment by saimaz** [comment]
Yes it is. (https://github.com/ongr-io/ElasticsearchBundle/blob/a6d1603fb8f19ae7acab848298d28ccc61672d05/Annotation/Document.php#L45)

Just simply use it in annotation.

**Comment by saimaz** [comment]
Currently `enable` option is available only for document.

**Comment by saimaz** [comment]
We will extend property annotation to allow to add `enable`.

**Comment by tautrimas** [comment]
Current workaround is to simply write `enabled="false"` in double quotes. Solved here.

**Comment by martiis** [comment]
Ofc, but now you should be able to type it correctly :)
