### ISSUE TITLE
Two bundles with the same document names conflicts in the same mapped manager

### ISSUE THREAD

**Issue by saimaz** [ongr-io/ElasticsearchBundle#313]

**Comment by dvondrak** [comment]
When two documents has the same name, properties from both documents are merged in the mapping. If one document uses type name, it works fine and separate mapping is created for both documents.

**Comment by saimaz** [comment]
Its not an option!

**Comment by GrandLTU** [comment]
Then there are few options:
- Include bundle name in repository mapping.
- Force users to use different index for same name documents.

**Comment by saimaz** [comment]
If there will be 2 document classes that define a same name of the elasticsearch type the exception will be thrown.
