### ISSUE TITLE
Lowercase type name problem

### ISSUE THREAD

**Issue by tautrimas** [ongr-io/ElasticsearchBundle#323]
When setting type name:

```php
/**
 * SuggestionModel holds suggestions info for object matches.
 *
 * @ES\Document(type="matchSuggestion")
 */
```

Type will be mapped as `matchsuggestion`. Is it a bug or a feature to lowercase type name?

**Comment by martiis** [comment]
As I remember it was a feature :)

**Comment by tautrimas** [comment]
It seems that this is important, because search queries are generated against lowercase version and index and type names are case-sensitive.
