### ISSUE TITLE
Property annotations not being validated anymore.

### ISSUE THREAD

**Issue by Zylius** [ongr-io/ElasticsearchBundle#341]
I can set
```php
    /**
     * @var CdnObject[]
     *
     * @ES\Property(
     *      name="enabled_cdn",
     *      multiple="string",
     *      objectName="AcmeTestBundle:CdnObject"
     * )
     */
    public $enabledCdn;
```
And the mapping will be passed to ElasticSearch although multiple should be a bool, not a string and type should always be set.

```php
    /**
     * @var string
     *
     * @Required
     */
    public $type;

    /**
     * @var bool OneToOne or OneToMany.
     */
    public $multiple;
```

Is this the expected behaviour since annotation camelizer?

**Comment by Zylius** [comment]
Checked this once again. It's caused by [AbstractAnnotationCamelizer](https://github.com/ongr-io/ElasticsearchBundle/blob/master/Mapping/AbstractAnnotationCamelizer.php) since it has a **constructor**. The situation is this:
* If you're using properties to define annotations (as in second code example above) you must not have a **constructor**, then DocParser will build Attribute objects using property annotations.
[Relevant code.]( https://github.com/doctrine/annotations/blob/master/lib/Doctrine/Common/Annotations/DocParser.php#L504)

* If you are using a **constructor**, Attributes must be set at object level  as an array of annotations, like in this [PR](https://github.com/ongr-io/ElasticsearchBundle/pull/89).  But according to discussion on the PR this isn't the way it should be implemented.  [Relevant code](https://github.com/doctrine/annotations/blob/master/lib/Doctrine/Common/Annotations/DocParser.php#L521)

Possible solutions for this that I can think of (we can't extend DocParser, it's final):

* Generate classes with annotations at object level and use them instead of the classes we're generating from. (tricky and messy)
* Contribute to doctrine.
* Just use annotations at the object level like in this [PR](https://github.com/ongr-io/ElasticsearchBundle/pull/89).

**Comment by martiis** [comment]
Only currently accepted solution would be *Just use annotations at the object*.

**Comment by martiis** [comment]
Also I think if we try to contribute to doctrine they would say "use attribute annotation" :)

**Comment by martiis** [comment]
I propose dropping snake case support for annotations. Only leave dumping part. @saimaz

**Comment by saimaz** [comment]
Completely agree @martiis
