### ISSUE TITLE
Can't get nested tophits aggregation.

### ISSUE THREAD

**Issue by Zylius** [ongr-io/ElasticsearchBundle#378]
Lets say we have a "terms" aggregation, and add "tophits" aggregation to it.
You can't loop through it cause https://github.com/ongr-io/ElasticsearchBundle/blob/master/Result/Aggregation/AggregationIterator.php#L75 is thrown.
Also the exception message has grammatical errors.
Nested iterators should have a converter passed as well.
Please fix this.
kthxbye

**Comment by saimaz** [comment]
Did you try with `find($path)` method?

**Comment by saimaz** [comment]
@Zylius i tryied to find a problem but seems like everything works normaly. Can you provide a test case where this problem occurs?
