### ISSUE TITLE
ConfigCache::__toString is deprecated

### ISSUE THREAD

**Issue by martiis** [ongr-io/ElasticsearchBundle#391]
https://github.com/ongr-io/FilterManagerBundle/issues/90

**Comment by tautrimas** [comment]
This article should help http://symfony.com/blog/new-in-symfony-2-7-phpunit-bridge.

**Comment by tautrimas** [comment]
Maybe it's better to add `"symfony/symfony": "~2.3,<2.7"` to `composer.json` for now?

**Comment by saimaz** [comment]
solved in v0.10
