### ISSUE TITLE
Object converting is inefficient

### ISSUE THREAD

**Issue by murnieza** [ongr-io/ElasticsearchBundle#400]
Say you want to load default ONGR's category tree with 1000 categories. This takes seconds to load which is not acceptable. Main bottleneck is conversion from raw ES data to ONGR Documents. RAW format cannot be used because it is not supported by category tree implementation.

Huge category tree is just an edge use case, but I believe that current implementation adds unreasonable amount of time to all actions related to conversion to Documents.

Maybe it is possible to introduce new results format (like simple_documents), which does not involve so complex conversion logics?

**Comment by saimaz** [comment]
Solved in #405
