### ISSUE TITLE
Missed methods in TermsAggregation

### ISSUE THREAD

**Issue by Dariusp** [ongr-io/ElasticsearchBundle#401]
Missed public  methods in class TermsAggregation (setSize, setOrder, setMinDocumentCount, setInclude,  setExclude). And test failing at ElasticsearchBundle/Tests/Unit/DSL/Aggregation/TermsAggregationTest.php line 60.

**Comment by saimaz** [comment]
All these fields can be set through `addParameter` function. We are trying to keep only mandatory fields in all DSL classes.
