### ISSUE TITLE
Implement Index Templates

### ISSUE THREAD

**Issue by martiis** [ongr-io/ElasticsearchBundle#41]
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/indices-templates.html

**Comment by saimaz** [comment]
Some how we need to think how it integrate in to the config. Combining together with document annotations. Lets put it to the Bench for now.

**Comment by laurusCN** [comment]
What a brill idea!

**Comment by saimaz** [comment]
Solved in #405
