### ISSUE TITLE
Command to switch aliases

### ISSUE THREAD

**Issue by tautrimas** [ongr-io/ElasticsearchBundle#421]
Do we have a command or workflow to quickly switch index alias after reimporting?

**Comment by martiis** [comment]
This is more of a technique which should be handled by users IMO. If some users might need a command like this they should code it them selfs. Technique is pretty basic:

```
POST http://es:9200/_aliases
```
```json
{
    "actions" : [
        { "remove" : { "index" : "index_name1", "alias" : "real_index" } },
        { "add" : { "index" : "index_name2", "alias" : "real_index" } }
    ]
}
```

We might only make a command which would set or remove alias.

**Comment by saimaz** [comment]
IMO console command to switch aliases is very usefull and should be in our bundle. I will try to add it in 1.0 version

**Comment by tautrimas** [comment]
Maybe we need not a specific command, but simply a console command:

```
ongr:es:execute --connection X --method POST --body BODY
```

Then, add some example bodies to documentation? There are so many usefull commands, like _close and _open, change various _settings, that I started thinking @martiis was right.

**Comment by saimaz** [comment]
Well, @tautrimas this is very universal solution. With this command you could do basicaly anything. And its completely the same as 
```
curl address:port/index/type -XPOST -d 'body'
```

**Comment by saimaz** [comment]
Alias switching is now implemented in the index creation. 

e.g. if you create an index with :

`app/console ongr:es:index:create -a -t` 

It will create an index with the time suffix, deletes all existing aliases of index name specified and creates a new one on the freshly created index.
