### ISSUE TITLE
Add --try flag to ongr:es:index:create command

### ISSUE THREAD

**Issue by martiis** [ongr-io/ElasticsearchBundle#423]
Then if index already exists exception should not be thrown, but a clear message outputed saying that index already exists or smth..

**Comment by kazgurs** [comment]
+1

**Comment by mvar** [comment]
Please give right name for this option. `--try` is misleading. As far as I understand the expected result is to create index or silently ignore exception if it is already created.

BTW, Doctrine has similar flag on `database:create` command. It's named `--if-not-exists`. Not sure about such name, but at least it's not misleading.

**Comment by ndinh215** [comment]
Yes, this is also my concern. "--if-not-exists" is correct option in Doctrine. Here, we just show error message instead of exception in the case of existing a certain index.

**Comment by saimaz** [comment]
Agree with @mvar `--try` doesn't say anything. `--if-not-exists` is more correct option name.

**Comment by ndinh215** [comment]
I fixed it, please review the PR https://github.com/ongr-io/ElasticsearchBundle/pull/535. Thanks.

**Comment by mvar** [comment]
From now on we have `--if-not-exists` flag to control if command should check for index existence or not.
