### ISSUE TITLE
Support for ElasticSearch Count API

### ISSUE THREAD

**Issue by N3m1s** [ongr-io/ElasticsearchBundle#425]
I see that your bundle does not support ES count API.

**Comment by tautrimas** [comment]
@N3m1s, maybe it can be simulated like this?

```php
$search->setSearchType('count');
$results = $repository->execute($search, Repository::RESULTS_RAW);
```

**Comment by N3m1s** [comment]
@tautrimas, thanks. But since official elastic search library does have a call to count API, I think it would be a more clearer approach to add this to your Repository class.

**Comment by tautrimas** [comment]
Yes yes, this is a workaround (:
