### ISSUE TITLE
Support for multi-search

### ISSUE THREAD

**Issue by tautrimas** [ongr-io/ElasticsearchBundle#427]
Feature request for https://www.elastic.co/guide/en/elasticsearch/reference/1.7/search-multi-search.html.

This should enable querying 50 queries at the same time in a single http request avoiding various overheads.

**Comment by saimaz** [comment]
Feature looks realy usefull. I'm adding it to the 1.1.0 milestone for now. Will check if that could be added sooner. btw PR's are welcome ;)
