### ISSUE TITLE
Implement Percolator

### ISSUE THREAD

**Issue by martiis** [ongr-io/ElasticsearchBundle#43]
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-percolate.html

**Comment by saimaz** [comment]
I don't see any real reason to use percolator.

**Comment by murnieza** [comment]
Please reconsider implementing percolators.

**Comment by tautelis** [comment]
Please revive this feature. Percolator is very well applied for user alert subscriptions when new items (matching their query) appear.

**Comment by saimaz** [comment]
Would be really nice to get a PR for the percolator support.
