### ISSUE TITLE
execute method is very type unsafe

### ISSUE THREAD

**Issue by tautrimas** [ongr-io/ElasticsearchBundle#434]
Method `\ONGR\ElasticsearchBundle\ORM\Repository::execute` returns wildly different types of results. Scrutinizer throws warnings all over the place and for a good reason. E.g.

> The return type of return $result; (ONGR\ElasticsearchBundle\Result\DocumentIterator|ONGR\ElasticsearchBundle\Result\RawResultIterator|array) is incompatible with the return type documented by MyCustomClass::getResults of type ONGR\ElasticsearchBundle\Result\DocumentIterator.

This happens if I explicitly define, which iterator I retrieve. There should be 3 separate methods for each return type and execute method marked deprecated.

We are using almost all variants of `execute` and from time to time encounter our own bugs due to type mismatch.

**Comment by tautrimas** [comment]
We implemented method name splitting and it started solving our type warnings. https://github.com/tautrimas/ElasticsearchBundle/pull/3. Method naming may not be the best, but still a good starting point.

**Comment by saimaz** [comment]
Looks very interesting. Thanks for sharing @tautrimas.

**Comment by saimaz** [comment]
Implemented.
