### ISSUE TITLE
_parent is missing when exporting data

### ISSUE THREAD

**Issue by martiis** [ongr-io/ElasticsearchBundle#440]
Also on import parent field is not being checked.

using v0.10.4

**Comment by martiis** [comment]
Also elasticsearch it self has an ability to export and import data but unreadable format
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html

**Comment by saimaz** [comment]
Snapshot is no a data export. It's a saved state of current index. You cannot transport a snapshot to a different cluster..

**Comment by saimaz** [comment]
I'm gonna check this issue with v1.0.0 release and will fix if there will be an issue.

**Comment by saimaz** [comment]
@martiis can you do a patch to v0.10 branch from my PR?

**Comment by martiis** [comment]
Ok
