### ISSUE TITLE
timeout configuration

### ISSUE THREAD

**Issue by ribb3r** [ongr-io/ElasticsearchBundle#454]
Please add some docs or provide an example about the configuration of:
* Search timeout:  
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html#_parameters_5  
* Connection timeout

**Comment by saimaz** [comment]
v0.9.3 & and v0.10.5 now supports timeout. Check #457 and #458

Use:
```php
$search->setTimeout(100);
```

For 1.0 version additions will be made in ElasticsearchDSL.
