### ISSUE TITLE
Converter throws an exception on empty objects

### ISSUE THREAD

**Issue by murnieza** [ongr-io/ElasticsearchBundle#459]
When document has field of type `object` and it's value is null the following exception is thrown:
>
ContextErrorException: Catchable Fatal Error: Argument 1 passed to ONGR\ElasticsearchBundle\Result\Converter::assignArrayToObject() must be of the type array, null given, called in /var/www/ongr-sandbox/vendor/ongr/elasticsearch-bundle/Result/Converter.php on line 107 and defined

Some kind of validation for empty objects has to be implemented.

**Comment by ndinh215** [comment]
Hi Murnieza, in this case, should we return null with the 1st argurment's null value?

**Comment by saimaz** [comment]
Converter has to create an empty `ObjectIterator` even there is no values for it.

**Comment by ndinh215** [comment]
OK, thks Saimaz.

**Comment by ndinh215** [comment]
I regenerated the exception case in the revision ~0.9, it did not show the exception. As Mantas's advice, I will inspect this issue in the dev-master revision. Thanks.

**Comment by ndinh215** [comment]
I inspected and detected that the error was caused in the case of the object field's null value & non multiple. It falls into the else clause in the following code: 

```PHP
if ($aliases[$name]['multiple']) {                               
    $value = new ObjectIterator($this, $value, $aliases[$name]); 
} else {                                                         
    $value = $this->assignArrayToObject(                         
        $value,                                                  
        new $aliases[$name]['namespace'](),                      
        $aliases[$name]['aliases']                               
    );                                                           
}

**Comment by ndinh215** [comment]
#489, it was fixed, please help me to review it. Thanks.
