### ISSUE TITLE
Print index mapping

### ISSUE THREAD

**Issue by saimaz** [ongr-io/ElasticsearchBundle#463]
We need an option in the index creation command with mapping info output to the cli. Equal to `app/console doctrine:schema:create --dump-sql`

**Comment by ndinh215** [comment]
In case of the option no-mapping's presence, we won't show info to the CLI with the option --dump.
And whats the format of the mapping output do you prefer?
For example: 
"mappings" : {
        "type1" : {
            "properties" : {
                "field1" : { "type" : "string", "index" : "not_analyzed" }
            }
        }
    }

Please give me your advice. Thanks.

**Comment by saimaz** [comment]
This issue is labeled with question so it means it's under discussion level. So in this case lets try to look at this more wide. When you want to create an index probably you dont need to see a mapping.. You might need it if you want to put mapping somewhere else or for debug reason.

Maybe we should create standalone command like `ongr:debug:*`?

Including @mvar and @murnieza.

**Comment by mvar** [comment]
IMHO we should have this feature in the same command or not to have it at all.

**Comment by murnieza** [comment]
I also think that this should be in same command. Format should be reusable when creating mapping manually.

**Comment by ndinh215** [comment]
OK thanks @mvar  & @murnieza , so whats your idea? @saimaz

**Comment by saimaz** [comment]
Ok. Lets see what options we have. 

* Add option `--dump-mapping` and create the index as normal with this option
* Add option `--dump-mapping` skip the index creation when option is added
* Is `--dump-mapping` option name makes sense?

**Comment by ndinh215** [comment]
I think the 1st option is more proper. Like Doctrine creation commands, it still creates objects and export SQL queries with the --dump-sql option's presence.

**Comment by murnieza** [comment]
Yes 1st option makes most sense. And name is clear enough.

**Comment by mvar** [comment]
@ndinh215 actually Doctrine works like described in 2nd option. I think we should go this way. From my personal experience the most common use case is to check schema/mapping before creating actual tables/indexes.

Few more ideas for option name:

- `--dump`
- `--dump-json`

**Comment by saimaz** [comment]
+1 for `--dump-json`

I agree with @mvar. If you are creating the index why do you need to see a mapping? The logcial solution would be to create the index as it is, or dump the json if you need to create it somewhere else or just see how it will be created. 

@ndinh215 @trandangtri what do you guys think?

**Comment by ndinh215** [comment]
With the purpose of index creation at somewhere from Json format, why we do not create export command, allowing Json output's exporting anytime we need, even this index created.

**Comment by ndinh215** [comment]
@mvar , yes surely Doctrine must generate SQL queries before executing these.

**Comment by trandangtri** [comment]
If I have to vote, I will vote for `--dump-json` and prefer the option 2

>  skip the index creation when option is added

If you need to review the mapping configuration as JSON before commit it into ES, let's use this option. As @mvar said, this is the way Doctrine is using.

But I have one concern, what will happen if I reviewed the mapping (ran this command), and really want to commit it? Try to run again? I'm afraid that the command will try to create `ES index` also. 

That's why in my opinion, I want to move this option to another command, such as: `ongr:mapping:create`, `ongr:mapping:update`. They focus on `mapping` too.

**Comment by saimaz** [comment]
Let's add option `--dump`, it's pretty obvious that will be only 1 format in elasticsearch and that is JSON, no need any hints for JSON or other formats.
