### ISSUE TITLE
Add _routing to bulk indexing

### ISSUE THREAD

**Issue by martiis** [ongr-io/ElasticsearchBundle#464]
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#bulk-routing

**Comment by saimaz** [comment]
Do you imagine how the usage should look like?

**Comment by martiis** [comment]
F.e. we are indexing a child_2 which parent_2 is a child_1 of another document (parent_1) then if we would like to check parent_2 children we would get nothing or at least a few. This doesn't work because parent_2 is sitting on parent_1 shard (it is it's child_1), but child_2 doesn't see that, so we need to set _routing to child_1 _parent or _routing.

**Comment by saimaz** [comment]
Yea, I know what is a routing in the bulk query :smiley:. By asking usage, I mean how our SDK should look like to use a routing with a bulk function.

e.g.:

```php
$content = new Content();
$content->id = 5; // Optional, if not set, elasticsearch will set a random.
$content->title = 'Acme title';
$manager->persist($content);
$manager->commit();
```

The exampel above creates a bulk query. Any idea how it should look like with a routing? I'm asking because if we will add this it has to look like easy to use.

**Comment by saimaz** [comment]
@martiis anything so far?

**Comment by martiis** [comment]
Sorry for delay. IMO it should look like setting a parent:

```php
$content = new Content();
$content->id = 5;
$content->title = 'Acme title';
$content->setRouting(2);
$manager->persist($content);
$manager->commit();
```

**Comment by mvar** [comment]
@martiis thanks for reply. This part probably would work right now by adding property with `@MultiField(name="_routing")` annotation. Maybe after one extra line [here](https://github.com/ongr-io/ElasticsearchBundle/blob/f21425e58f6f896546df27cbbd4ee6c70707d81b/Service/Manager.php#L355) for `_routing`.

Don't forget that you MUST provide routing not only for __indexing__ but also every time when you are __getting__, __deleting__, or __updating__ the document. After we update `bulk()`, indexing, updating and deleting operations should be covered. Document getting using routing could be implemented by adding `routing` query parameter support in `Search` class.
