### ISSUE TITLE
Do not send empty mapping to elasticsearch

### ISSUE THREAD

**Issue by mvar** [ongr-io/ElasticsearchBundle#467]
**elasticsearch** throws exception when empty mapping is given. This could happen when you have connection which is not associated with any document and you try to create index for that connection.

Current (invalid) request data:

```json
{
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 0,
    "index": {
      "refresh_interval": -1
    }
  },
  "mappings": []
}
```

Results in error:

```json
{
    "error": "ClassCastException[java.util.ArrayList cannot be cast to java.util.Map]",
    "status": 500
}
```

Request should look like this (no empty mapping):

```json
{
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 0,
    "index": {
      "refresh_interval": -1
    }
  }
}
```

Possible place for fix: https://github.com/ongr-io/ElasticsearchBundle/blob/b616d6f6e9673d55e246da190dfdd65aa4986f8f/Service/Manager.php#L393

**Comment by saimaz** [comment]
Would be nice if elastocsearch-php or event the elastcsearch database invalidate it by itself. Sent an empty mapping array for me looks quite ok.

**Comment by murnieza** [comment]
`elasticsearch-php` checks only if mapping [is not `null`](https://github.com/elastic/elasticsearch-php/blob/7b9cf8c7fcac781ccca0688fb73591f626fe1a8a/src/Elasticsearch/Endpoints/Indices/Create.php#L27). Exception from Elasticsearch is not readable: 

```bash
[Elasticsearch\Common\Exceptions\ServerErrorResponseException]
ClassCastException[java.util.ArrayList cannot be cast to java.util.Map]
```

I think it makes sense to implement checking on our side.

**Comment by mvar** [comment]
@murnieza I think so too.
