### ISSUE TITLE
return documents id's in the commit() return

### ISSUE THREAD

**Issue by saimaz** [ongr-io/ElasticsearchBundle#470]
Would be usefull to get all isnerted elasticsearch document id's after commit. By default it returns `raw` response. What if we would add an option in the commit to return id's list.

**Comment by asev** [comment]
[Commit from `bulk()` method is implemented](https://github.com/ongr-io/ElasticsearchBundle/blob/v1.0.0-alpha.4/Service/Manager.php#L364). So, you should consider, that after direct `commit()` call you will get ids from the last bulk chunk only.

Also this would conflict with possible solution of https://github.com/ongr-io/Demo/issues/154.

**Comment by saimaz** [comment]
The biggest problem of this feature is to set ID's to the persisted documents. While you can add more than one document to the bulk container it's quite complex to set specific id's to every single persisted object.

IMO we should stick simple response for now and return just ID's. Additionally, we should throw the exception if any error occurs (issue #648 ).

**Comment by saimaz** [comment]
After long discussions, we decided to not modify persisted document objects. It's too complex to do it and costs too much of the performance. If there are any need to get id's then it can be grabbed from Elasticsearch response.
