### ISSUE TITLE
Can't set NestedAggregation without inner aggregation

### ISSUE THREAD

**Issue by imvaid** [ongr-io/ElasticsearchBundle#473]
Can't add NestedAggregation without adding inner aggregation even though it's valid. Exception gets thrown:
https://github.com/ongr-io/ElasticsearchBundle/blob/v0.10.5/DSL/Aggregation/NestedAggregation.php#L61-L63

Nested aggregation without inner aggregation just returns nested documents count.

**Comment by saimaz** [comment]
Wrong place. It has to be in Elasticsearch DSL.

Fixed in https://github.com/ongr-io/ElasticsearchDSL/pull/80
