### ISSUE TITLE
Support 'completion' type in ES-document

### ISSUE THREAD

**Issue by trandangtri** [ongr-io/ElasticsearchBundle#477]
In the past, we supported 'completion' type in all ES-document (version 0.9.*), but not now. Please bring it back to the latest version.

**Version**: dev-master

**Comment by murnieza** [comment]
As mentioned [here](https://github.com/ongr-io/ElasticsearchBundle/blob/65d6405ccb2cbd7fb79da9ef42745e9fdd39cd0f/Resources/doc/index.md#some-news-for-upcoming-versions) and [here](https://github.com/ongr-io/ElasticsearchBundle/blob/65d6405ccb2cbd7fb79da9ef42745e9fdd39cd0f/Resources/doc/upgrade.md) `Suggestions` were removed and will be implemented with 1.1.0 version.

**Comment by einorler** [comment]
Implemented in #658
