### ISSUE TITLE
Return the result of all committing to ES

### ISSUE THREAD

**Issue by trandangtri** [ongr-io/ElasticsearchBundle#482]
So far, all committing data (CRUD) to ES are in silent. It should return the result code for checking, for instance. That's why we cannot make sure the output of our bulk operation was successful or not, such as importing data from a broken JSON file, APIs, etc.

Thanks @asev, @murnieza for explaining to me.

**Comment by saimaz** [comment]
There is already an issue about what should be returned after commit #470

**Comment by trandangtri** [comment]
You're right @saimaz. I will close this and follow on #470
