### ISSUE TITLE
Set document ID after commit to ES

### ISSUE THREAD

**Issue by mvar** [ongr-io/ElasticsearchBundle#484]
```php
$document = new CustomDocument();

$manager->persist($document);
$manager->commit();

var_dump($document->getId());
```

Currently this code returns `NULL`. It would be nice to get generated ID.

**Comment by mvar** [comment]
Relates to #470

**Comment by saimaz** [comment]
I cannot find a way how to implement it without loosing performance. @einorler tried to do that with events, but still performance loss is around 30%..

**Comment by saimaz** [comment]
@mvar, any thoughts about this issue?

**Comment by mvar** [comment]
@saimaz, nope. I just think that this would be really nice to have.

**Comment by saimaz** [comment]
It's too complicated and costs performance. If user really needs an id after commit it can do it by itself via event listener.
