### ISSUE TITLE
Add support for document getters with "is" prefix

### ISSUE THREAD

**Issue by mvar** [ongr-io/ElasticsearchBundle#485]
It's common practice to have `setFoo()` and `isFoo()` methods for boolean variables. Currently only `get` prefix is supported.

Code reference: https://github.com/ongr-io/ElasticsearchBundle/blob/65d6405ccb2cbd7fb79da9ef42745e9fdd39cd0f/Mapping/DocumentParser.php#L187

**Comment by asev** [comment]
By the way, there were similar issues in the past. Check #132 and #58
