### ISSUE TITLE
Add remove() method for manager

### ISSUE THREAD

**Issue by mvar** [ongr-io/ElasticsearchBundle#486]
Here is no easy way to remove document from ES when you have only document object. It would be nice to have method in `Manager` service:

```php
public function remove(DocumentInterface $document);
```

This method should add delete operation to bulk request body.

**Comment by saimaz** [comment]
There is similar method already: https://github.com/ongr-io/ElasticsearchBundle/blob/65d6405ccb2cbd7fb79da9ef42745e9fdd39cd0f/Service/Repository.php#L287

**Comment by mvar** [comment]
Similar in purpose, but there are two differences in usage:

1. To use `Repository::remove()` you need to have repository service or to know document type.
2. `Repository::remove()` directly calls ES. In some cases would be nice to use bulk request.

I think we should implement `Manager::remove()` as I suggested. Not sure about method in `Repository` class. As ESB was created with objects in mind maybe we should remove it.
