### ISSUE TITLE
Remove multiple types support from Repository class

### ISSUE THREAD

**Issue by mvar** [ongr-io/ElasticsearchBundle#487]
Currently multi-type support is used only for search and delete queries. When repository is configured as multi-type it is quite useless for other operations.

We should find a method how to execute search and delete queries without multi-type repository.

Until we find good solution for this, we could create separate class for multi-type repository. This way we would have clear repository class.

**Comment by saimaz** [comment]
Current implementation brakes ideology of repository pattern and view from objective perspective. I propose to remove multi type support in `Repository` from `1.0.0` version. During last year I barely saw any usage with this functionality. By removing it we will have time to think how to add a good support for it if its needed at all. As a backup plan there is a public access to the elasticsearch-php client.
