### ISSUE TITLE
Close scroll explicitly after unfinished iteration

### ISSUE THREAD

**Issue by tautrimas** [ongr-io/ElasticsearchBundle#488]
After running a search and iterating results only partially, we would like to free the current scroll. See: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html#_clear_scroll_api.

This is needed, because we are using quite large timeouts, but iterating only first few hundred results. It would be nice, if `DocumentScanIterator` had a destructor or a public method that explicitly and conveniently closed no longer unused scroll.

**Comment by saimaz** [comment]
Yep, desturctor in scroll operation with large timeouts makes sense. We'll take a look how to implement it.

**Comment by murnieza** [comment]
Just a remark. `elastcisearch-ph`p client already does that in [iterator helpers](https://github.com/elastic/elasticsearch-php/blob/7b9cf8c7fcac781ccca0688fb73591f626fe1a8a/src/Elasticsearch/Helper/Iterators/SearchResponseIterator.php#L70). I do not think that using this helper there is a good idea, but that can be used as a reference when implementing this feature.

**Comment by murnieza** [comment]
This will be implemented after https://github.com/ongr-io/ElasticsearchBundle/issues/487.
