### ISSUE TITLE
Scrutinizer is failing

### ISSUE THREAD

**Issue by tautrimas** [ongr-io/ElasticsearchBundle#496]
All inspections are failing https://scrutinizer-ci.com/g/ongr-io/ElasticsearchBundle/inspections. This is related to DSL parsing bug.

On our side, all projects, that depend on ONGR ElasticsearchDSL are failing too just because of this issue.

**Comment by saimaz** [comment]
I'm gonna report this to the scrutinizer team. If we won't find a solution and scruitinizer won't fix this we are going to remove the scrutinizer check. Due this error every single PR check in our organisation fails.

**Comment by mvar** [comment]
This issue was resolved on Srutinizer's side.
