### ISSUE TITLE
Ensure support for ES 2.0

### ISSUE THREAD

**Issue by saimaz** [ongr-io/ElasticsearchBundle#501]
Relates to teh bug here: https://github.com/ongr-io/ElasticsearchBundle/issues/493

**Comment by kazgurs** [comment]
ongr-io/ElasticsearchBundle/issues/453

**Comment by saimaz** [comment]
@kazgurs this issue is about software support, not for travis testing. But yeah, maybe long description should be more clear..

**Comment by mvar** [comment]
Currently all features are tested and working on Elasticsearch 2.1.1. If we are missing some new features, they will be added in next minor release of ESB.
