### ISSUE TITLE
Private Embedded, bug?

### ISSUE THREAD

**Issue by tadcka** [ongr-io/ElasticsearchBundle#524]
Example:
/**
     * @var AttributeNested[]
     *
     * @ES\Embedded(name="attributes", class="NfqCatalogBundle:AttributeNested", multiple=true)
     */
    private $attributes = [];

Error:
 [Symfony\Component\Debug\Exception\ContextErrorException]                        
  Notice: Undefined property: ONGR\ElasticsearchBundle\Annotation\Embedded::$type

**Comment by mvar** [comment]
This was fixed few minutes ago. Please try with latest version

**Comment by saimaz** [comment]
@tadcka `master` branch is a development version which might change a lot, my advice would be to use alpha tagged version. Also might be that today I will release a new alpha version.

btw, ElasticsearchBundle is at the end of the milestone so stable version will be released very soon.

**Comment by tadcka** [comment]
Thanks!
