### ISSUE TITLE
Clearing not existing scroll will throw an exception

### ISSUE THREAD

**Issue by murnieza** [ongr-io/ElasticsearchBundle#526]
After solving #488, because of [this destructor](https://github.com/ongr-io/ElasticsearchBundle/blob/f21425e58f6f896546df27cbbd4ee6c70707d81b/Result/AbstractResultsIterator.php#L104) an exception will be thrown when scroll does not exist (was fully iterated, expired or any other reason).

Similar problem was known in https://github.com/elastic/elasticsearch-php/issues/342 and is already resolved, I think we need to go the same way.

**Comment by mvar** [comment]
Looks like newer versions of Elasticsearch PHP client (v2.0+) handles this automatically.
