### ISSUE TITLE
Enumerate supported meta fields in @MetaField annotation

### ISSUE THREAD

**Issue by mvar** [ongr-io/ElasticsearchBundle#531]
Make sure user doesn't use meta fields we don't support.

Also it would be nice to create dedicated documentation page about these supported fields.

**Comment by saimaz** [comment]
@mvar do you think we could do that in `1.1` milestone instead?

**Comment by mvar** [comment]
I will make a PR in minutes. That's not a big job.

**Comment by mvar** [comment]
This no more makes sense because of #533
