### ISSUE TITLE
Query log in profiler does not work

### ISSUE THREAD

**Issue by mvar** [ongr-io/ElasticsearchBundle#552]
I have installed ESB and filter manager on fresh Symfony 3.0 application. Everything runs smoothly, but query log always shows __0__.

**Comment by mvar** [comment]
Well, actually it works. After I have added `profiler: true` in my configuration. I will add this line to documentation.

But there is an issue still. Why do we show extra tab in profiler when ESB profiling is disabled?

**Comment by saimaz** [comment]
Well, the profiler toggling option was only an idea. Maybe we do not need it at all. Maybe profiler could be enabled by default.

**Comment by saimaz** [comment]
anyway it injects in debug toolbar which in prod environment is not loaded at all, so not a problem at all..
