### ISSUE TITLE
Add a way to fully use Elasticsearch 2.0 features

### ISSUE THREAD

**Issue by mvar** [ongr-io/ElasticsearchBundle#556]
Officially we support Elasticsearch 1.* and 2.*, but actually user can not completely use Elasticsearch 2.0 features. For example, filters uses deprecated "filtered query". I'm not sure if this affects performance from Elasticsearch side, but it definitely affects user experience from our side - despite which ES version you are using, you will get errors about deprecated code.

**Comment by saimaz** [comment]
It's too complicated to support both versions with so many changes. I propose to support from 2.0, ElasticseachDSL will support also only from 2.0 so that makes sense. 

If user wants to use elasticsearch 1.* he could use 0.10 or some 1.0 alpha version.

**Comment by mvar** [comment]
ElasticsearchBundle v1.0 will require Elasticsearch v2.0. Closing issue.
