### ISSUE TITLE
Cannot add custom analyzer to document

### ISSUE THREAD

**Issue by Emirii** [ongr-io/ElasticsearchBundle#562]
Hello, I am using current dev-master (alpha 7) with current dev dependencies. 

I have tried to follow the documents and tutorials as closely as possible, but I keep running into this error:
<pre>
$ php app/console ongr:es:index:create

  [Elasticsearch\Common\Exceptions\BadRequest400Exception]
  mapper_parsing_exception: Mapping definition for [original_title] has unsupported parameters:  [index_analyz
  er : incrementalAnalyzer]

  [Elasticsearch\Common\Exceptions\BadRequest400Exception]
  {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Mapping definition for [original_title]
   has unsupported parameters:  [index_analyzer : incrementalAnalyzer]"}],"type":"mapper_parsing_exception","r
  eason":"Failed to parse mapping [ad]: Mapping definition for [original_title] has unsupported parameters:  [
  index_analyzer : incrementalAnalyzer]","caused_by":{"type":"mapper_parsing_exception","reason":"Mapping defi
  nition for [original_title] has unsupported parameters:  [index_analyzer : incrementalAnalyzer]"}},"status":
  400}
</pre>

**Composer:**
<pre>
       "symfony/symfony": "2.7.*",
        "ongr/elasticsearch-dsl": "dev-master",
        "ongr/elasticsearch-bundle": "dev-master",
</pre>

**My current elasticsearch installed is:**
<pre>
{
  "name" : "Copycat",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.1.1",
    "build_hash" : "40e2c53a6b6c2972b3d13846e450e66f4375bd71",
    "build_timestamp" : "2015-12-15T13:05:55Z",
    "build_snapshot" : false,
    "lucene_version" : "5.3.1"
  },
  "tagline" : "You Know, for Search"
}
</pre>

**My Config is:**
<pre>
ongr_elasticsearch:
    analysis:
        filter:
            incremental_filter:
                type: edge_ngram
                min_gram: 1
                max_gram: 20
        analyzer:
            incrementalAnalyzer:
                type: custom
                tokenizer: standard
                filter:
                    - lowercase
                    - incremental_filter
    connections:
        default:
            index_name: acme_index
            hosts:
                - 192.168.99.99
            analysis:
                analyzer:
                    - incrementalAnalyzer
                filter:
                    - incremental_filter
    managers:
        default:
            connection: default
            mappings:
                - ApplicationAdBundle
</pre>

**My Document is:**
<pre>
namespace Application\AdBundle\Document;

use ONGR\ElasticsearchBundle\Annotation as ES;

/**
 * @ES\Document(type="ad")
 */
class Ad
{
    /**
     * @var string
     *
     * @ES\Id()
     */
    public $id;

    /**
     * @ES\Property(
        type="string",
        name="original_title",
        options={"index_analyzer":"incrementalAnalyzer"}
      )
     */
    public $title;
}
</pre>

The bundle works great without any custom analyzers, but for my project it is necessary.

Please, if you could offer to point out what I am doing wrong or any assistance, that would be great! I would much rather use the updated version of Elasticsearch rather than the out of date 1.x other bundles currently only provide. Thanks and good work so far!

**Comment by Emirii** [comment]
I figured it out!! Reading Elasticsearch documentation, the new version now has "analyzer" instead of "index_analyzer", so documentation should be updated.

This is correct:
<pre>
    /**
     * @ES\Property(
        type="string",
        name="original_title",
        options={"analyzer":"incrementalAnalyzer"} 
      )
     */
    public $title;
</pre>

**Comment by saimaz** [comment]
Thanks for the find. I'll fix the docs. 

p.s. when you define `options` whenever is inside it will be passed directly to elasticsearch mapping, so it's equal to original elasticsearch docs.
