### ISSUE TITLE
Alias switch is not atomical

### ISSUE THREAD

**Issue by damienalexandre** [ongr-io/ElasticsearchBundle#570]
When using `app/console ongr:es:index:create -a -t`, here is what happens:

1. we create a new index with a date suffix
2. we put an alias on it
3. we remove this alias from older indexes

The issue is that search and indexation can still happens between step 2 and 3.

For a search, it's not a big deal (you just hit twice the shards you expect to hit), but for indexing Elasticsearch will throw an error because you can't index on an alias which point to multiple indexes.

All aliases operations should be done in one call, with the _aliases API:

```
curl -XPOST 'http://localhost:9200/_aliases' -d '
{
    "actions" : [
        { "remove" : { "index" : "test1", "alias" : "alias1" } },
        { "add" : { "index" : "test1", "alias" : "alias2" } }
    ]
}'
```

This API makes sure there is no gap between the remove and add command.

**Comment by saimaz** [comment]
Thanks for the notice.
