### ISSUE TITLE
Get document sort field results

### ISSUE THREAD

**Issue by Emirii** [ongr-io/ElasticsearchBundle#573]
Hello, I would like to get the document's sort field in results, but so far I believe there isn't a method to do this. It is returning the sort field as an array in the protected documents property on search results but I can't figure out how to get the value. 

https://www.elastic.co/guide/en/elasticsearch/guide/current/sorting-by-distance.html

something like:
```
            foreach ($results as $doc) {
                $distance = $doc->getSort();
            }
```

**Comment by Emirii** [comment]
I have proposed a change that adds this functionality to it, in case there wasnt any other way to do this. It so far has worked good for me!

https://github.com/ongr-io/ElasticsearchBundle/compare/master...Emirii:patch-1

**Comment by saimaz** [comment]
Good catch, it will be fixed in the next release. Thanks.
