### ISSUE TITLE
Document properties annotations Options are not processed

### ISSUE THREAD

**Issue by kaminski** [ongr-io/ElasticsearchBundle#574]
I'm trying add the fields option to one of my fields like as suggested in the documention like so: 

```
    /**
     * @ES\Property(
        type="string",
        name="title",
        options={"fields":{"raw":{"type":"string","index":"not_analyzed"}}}
      )
     */
     $title
```

Hoever the optioins are simply disregarded. Am I missing something or should it work like this? 

I'm refering to this section in the documention
[ElasticsearchBundle/Resources/doc/mapping.md](https://github.com/ongr-io/ElasticsearchBundle/blob/master/Resources/doc/mapping.md#document-properties-annotations)

**Comment by saimaz** [comment]
It should work as you described. I will check with the exact example how you provided and let you know.

**Comment by kaminski** [comment]
Thank you very much for the lightning-fast response. Btw, it is really fantastic bundle you are providing here.

**Comment by saimaz** [comment]
Everything works as expected. The only thing is missing, that a doc about multi fields usage. But actually it's the same as in elasticsearch, ElasticsearchBundle is nothing different. I will write a docs topic about multi fields usage in a few days.

**Comment by saimaz** [comment]
In short by your example:

```
     /**
     * @ES\Property(
        type="string",
        name="title",
        options={"fields":{"raw":{"type":"string","index":"not_analyzed"}}}
      )
     */
     $title
```

`title` - use this field for indexing
for search, you have to use key `title.raw`, and you can use this field, `title` won't work
in result you will get array with `title` or a document object

I hope it's clear enough ;)

**Comment by kaminski** [comment]
Yes, this is how I expected it to work. But I can't see this structure when I check the mapping of the type in elasticsearch. I did the following 

- created a new index
- index documents with elasticsearchBundle
- looked at /myIndex/_mappings/myType 

and the mapping for the "title" field looks like this: 

```
          "title": {
            "type": "string"
          },
```
Shouldn't the mapping in my example reflect the field title.raw ?

**Comment by saimaz** [comment]
It should look like:

```json
...
"title": {
    "type": "string",
    "fields": {
        "raw": {
            "index": "not_analyzed",
            "type": "string"
        }
    }
}
...
```

What version of elasticsearch you are using and which version of bundle?

**Comment by kaminski** [comment]
I'm using 

- Elasticsearch2.1.0
- ongr/elasticsearch-bundle": "~1.0.0-alpha.6

**Comment by saimaz** [comment]
I can confirm that with Elasticsearch 2.1 and with both ElasticsearchBundle 1.0.0-alpha.6 and 1.0.0-alpha.7 everything works. It's very interesting why you don't get fields value in the index mapping. Could you debug index create console command and look what output comes here https://github.com/ongr-io/ElasticsearchBundle/blob/77e264a55c97608765acf6935b86e9fdb9507d85/Service/ManagerFactory.php#L77 for your specific manager. This is the starting point to catch a bug or a problem :). The only thing I can think of is that you are running on prod env and index mappings are cached with the older structure without fields option.

**Comment by kaminski** [comment]
Got it, thank to your suggestion. The problem was, that I created the index on elastic search directly and not via `bin/console ongr:es:index:create` . Since everything else worked as expected I didn't suspect that anything wrong with doing that. 

Thank you very much indeed for your help!
