### ISSUE TITLE
Add support for 'is' getter for bool type document fields.

### ISSUE THREAD

**Issue by gimikus** [ongr-io/ElasticsearchBundle#58]
Add support for 'is' getter for bool type document fields (getActive() => isActive()).
Now when document have private bool type field ($active) ElasticsearchBundle check is declarated set and get methods (getActive(), setActive()) for it. 
https://github.com/ongr-io/ElasticsearchBundle/blob/master/Mapping/MetadataCollector.php#L257

**Comment by saimaz** [comment]
#132
