### ISSUE TITLE
Performance issue MetadataCollector getMappings called on every DocumentIterator iteration

### ISSUE THREAD

**Issue by sidux** [ongr-io/ElasticsearchBundle#598]
the convertToDocument function is called multiple times on iterator under the hood it parses the project annotations, i don't it has to be called that mach.

**Comment by saimaz** [comment]
Are you sure in prod env it calls every time? It has to be written in cache and grab every time from there..

**Comment by sidux** [comment]
Got it, yep there is a cache but i had to activate it in config : 
```yml
ongr_elasticsearch:
    cache: true
```
default value in MetadataCollector class is set to false

**Comment by saimaz** [comment]
default value should be `%kernel.debug%`

**Comment by saimaz** [comment]
@sidux is this problem still exists for you? Any news?

@einorler can you double check this issue?

**Comment by einorler** [comment]
Checked it. It is set to false by default:

https://github.com/ongr-io/ElasticsearchBundle/blob/b628264af59704c654e067ed6b53e178545f5256/DependencyInjection/Configuration.php#L34

Will fix it
