### ISSUE TITLE
Memory leak in CollectionHandler

### ISSUE THREAD

**Issue by mvar** [ongr-io/ElasticsearchBundle#617]
When I'm running process (with debug disabled) which makes huge amount of Elasticsearch queries, memory starts to grow. This problem goes away when I comment-off this line:

https://github.com/ongr-io/ElasticsearchBundle/blob/b305614610c264e4da6b3097b536c383e15d6add/Profiler/Handler/CollectionHandler.php#L31

This class is used as a logger handler for tracer [passed](https://github.com/ongr-io/ElasticsearchBundle/blob/b305614610c264e4da6b3097b536c383e15d6add/Service/ManagerFactory.php#L89) to Elasticsearch client service. Shouldn't that `es.tracer` [service](https://github.com/ongr-io/ElasticsearchBundle/blob/b305614610c264e4da6b3097b536c383e15d6add/Resources/config/services.yml#L43) be disabled at all when debug is disabled?

**Comment by mvar** [comment]
Also memory keeps growing while executing `ongr:es:index:import`:

```
$ bin/console ongr:es:index:import index.json -vvv --no-debug
  1300/18101 [==>-------------------------]   7%  1 sec/14 secs 18.0 MiB
  2500/18101 [===>------------------------]  13% 2 secs/14 secs 26.0 MiB
  8400/18101 [============>---------------]  46% 6 secs/13 secs 64.0 MiB
 18101/18101 [============================] 100% 13 secs/13 secs 124.0 MiB
```

**Comment by tautrimas** [comment]
This issue disappears if you run with `-e prod`. See https://github.com/elastic/elasticsearch-php/issues/204

**Comment by mvar** [comment]
@tautrimas thanks for your input. Currently the problem comes from ONGR. In the initial comment I have left this link:

https://github.com/ongr-io/ElasticsearchBundle/blob/b305614610c264e4da6b3097b536c383e15d6add/Service/ManagerFactory.php#L89

What's the point to set tracer if debug is disabled? When we don't set tracer here, memory usage is consistent.

About `dev` environment. I can not think of any "bad" things against running "big" scripts in `dev` environment. You can control logging (and usually memory usage) by setting `--no-debug` flag. `dev` environment is here to make your life easier. While running scripts in dev environment you don't need to care about cache clearing.

**Comment by saimaz** [comment]
@mvar is right. It is a bug, tracer should not be set if the debug is turned off.
