### ISSUE TITLE
Index drop in IndexImportCommandTest.php

### ISSUE THREAD

**Issue by einorler** [ongr-io/ElasticsearchBundle#620]
There is an irrational drop of index in both tests in IndexImportCommandTest.php, after that, the tests attempts to execute a search to the freshly dropped index:
https://github.com/ongr-io/ElasticsearchBundle/blob/b305614610c264e4da6b3097b536c383e15d6add/Tests/Functional/Command/IndexImportCommandTest.php#L76

This results in 7 tests 0 assertions. What is even more alarming is that after trying to comment these lines out, the tests fail and the apparent reason is that the data is not being loaded to the ES.

**Comment by saimaz** [comment]
Fixed in 5.0 rc
