### ISSUE TITLE
Parent documents not working

### ISSUE THREAD

**Issue by dennis-hh** [ongr-io/ElasticsearchBundle#623]
Hey,
I'm struggling to get parent relations to work.

I have two very simple documents: User and InstallEvent. The parent of InstallEvent is like this:

```
/**
 * @ES\ParentDocument(class="FooBundle\ElasticSearch\Document\User")
*/
    private $user;
```
Persisting looks like this:
```
$userDocument = new FooBundle\ElasticSearch\Document\User();
$userDocument->setId($someId));
$this->elasticSearchManager->persist($userDocument);
$event = new FooBundle\ElasticSearch\Document\InstallEvent();
$event->setCreatedAt(new \DateTime());
$event->setUser($someId);
$this->elasticSearchManager->persist($event);
$this->elasticSearchManager->commit();
```

It breaks on commit():
```
illegal_argument_exception: Can't specify parent if no parent field has been configured
```
It appears that the special _parent field is not written to the mapping of the index. This is what the index looks like when I do not call setUser() on $event:
```
{
  "statistics": {
    "aliases": {

    },
    "mappings": {
      "install_event": {
        "properties": {
          "created_at": {
            "type": "date",
            "format": "strict_date_optional_time||epoch_millis"
          },
        }
      },
      "user": {
        "properties": {
          "id": {
            "type": "long"
          }
        }
      }
    },
    "settings": {
      "index": {
        "creation_date": "1462796309474",
        "number_of_shards": "1",
        "number_of_replicas": "0",
        "uuid": "C6_cVv-hQU6507wZjgXYWw",
        "version": {
          "created": "2020299"
        }
      }
    },
    "warmers": {

    }
  }
}
```
According to the documentation at https://www.elastic.co/guide/en/elasticsearch/guide/current/parent-child-mapping.html, there should be a "_parent" field.

Furthermore, the mapping remains empty when I call `console ongr:es:index:create`:
```
{
  "statistics": {
    "aliases": {

    },
    "mappings": {

    },
    "settings": {
      "index": {
        "creation_date": "1462797974193",
        "number_of_shards": "1",
        "number_of_replicas": "0",
        "uuid": "EJh2PCB_S7OaEysCM69B0A",
        "version": {
          "created": "2020299"
        }
      }
    },
    "warmers": {

    }
  }
}
```
Mappings is filled only after persisting the first document.

Am I missing something?

**Comment by saimaz** [comment]
I think you found a bug. 

Can you try to not use `ElasticSearch` in `new FooBundle\ElasticSearch\Document\User()`. something with `Bundle` suffix should be before `Document` folder. Might be the issue because of this.

@mvar do you know is there something missing with the parent? I'm not 100% sure if you need something to setup at the parent document class settings.

**Comment by dennis-hh** [comment]
Yup, that was it. Sub namespaces are not supported, as the metadata collector only looks for a "Document" folder inside the bundle folder. Thanks! :)

**Comment by saimaz** [comment]
Good to know that it helped. ;)

**Comment by dennis-hh** [comment]
I have a followup problem now:
This is the index being written by the bundle:
```
{
  "statistics": {
    "aliases": {

    },
    "mappings": {
      "install_event": {
        "_parent": {
          "type": "User"
        },
        "_routing": {
          "required": true
        },
        "properties": {
          "created_at": {
            "type": "date",
            "format": "strict_date_optional_time||epoch_millis"
          }
        }
      },
      "user": {
        "properties": {
        }
      }
    },
    "settings": {
      "index": {
        "creation_date": "1462801632412",
        "number_of_shards": "1",
        "number_of_replicas": "0",
        "uuid": "kR99GYHGSzK4GfWzPGSBaA",
        "version": {
          "created": "2020299"
        }
      }
    },
    "warmers": {

    }
  }
}
```
The parent type of "install_event" is "User", but it should be "user". This results in errors like this when doing a has_child query (has_parent query is also not working):
```
"type": "query_parsing_exception",
"reason": "[has_child]  Type [install_event] points to a non existent parent type [User]",
```
The source seems to be `\ONGR\ElasticsearchBundle\Mapping\DocumentParser::getDocumentType`, where the short name of the reflection class is taken, but it is not lowercase'd.

**Comment by saimaz** [comment]
Now that seems actually a bug indeed. It has to be lowercased. I'll take a look tomorrow. If you have time and know what to do, you may provide a fix. It's an easy fix.

**Comment by mvar** [comment]
Known place :)

https://github.com/ongr-io/ElasticsearchBundle/blob/master/Mapping/DocumentParser.php#L102

`getDocumentType()` should also use `Caser::snake()`.

**Comment by saimaz** [comment]
But what if a user defines the document type in upper case in the class annotation? :)

**Comment by mvar** [comment]
@saimaz we generate type name from short name of the class only if type name is not defined by the user. Earlier mentioned `snake()` is only needed for generated value.

**Comment by saimaz** [comment]
Added `Caser:snake` to the `getDocumentType()` method solves the issue.
