### ISSUE TITLE
Query given in profiler is not executable

### ISSUE THREAD

**Issue by mvar** [ongr-io/ElasticsearchBundle#624]
Snippet of the query:

```json
"reverse": {
    "reverse_nested": [],
    "aggregations": {
        "foo": {
            "terms": {
               "field": "id"
            }
       },
```

Error:

```
"type": "search_parse_exception",
"reason": "Expected [START_OBJECT] under [reverse_nested], but got a [START_ARRAY] in [reverse]",
```

Somehow `reverse_nested` is printed as array instead of object (probably all other empty objects too). Query execution using ESB works, just query given in the profiler is broken.

I guess problem comes from this line:
https://github.com/ongr-io/ElasticsearchBundle/blob/b305614610c264e4da6b3097b536c383e15d6add/Profiler/ElasticsearchProfiler.php#L176

**Comment by saimaz** [comment]
Very precise guess I would say. IMO we should not use standard JSON encode or decode but use `elasticsearch-php` serializer and deserializer. For sure they would handle it in right order.
