### ISSUE TITLE
Cannot find or delete if document has a parent

### ISSUE THREAD

**Issue by dennis-hh** [ongr-io/ElasticsearchBundle#626]
Hey,
it seems that it is not possible to directly use the manager's `find()` method if the document being searched has a parent. It always results in `routing is required for [fooIndex]/[BarDocument]/[123]`. The same is true for repository operations.

When trying to delete such a document via `$elasticsearchManager->remove($document)`, the document is NOT deleted, and the method call does not raise an exception.

From my point of view, it should either be possible to add the parent id as an optional parameter, or even better, let the bundle handle it internally. If a document has a parent, just add `?parent=someParentId` to the call.

I'm currently using this workaround:

```
$query = [
     '_id' => $document->getId(),
     '_parent' => $document->getParent(),
];
$elasticsearchManager->bulk('delete', 'BarDocument', $query);
```

**Comment by saimaz** [comment]
Apparently, parent-child doesn't work correctly since it has to be indexed in the same shard by providing the routing. I'm sorry but I won't add this to the v5, maybe it will be introduced in the v6.
