### ISSUE TITLE
Refresh on all indexes increases server load ~3x

### ISSUE THREAD

**Issue by tautrimas** [ongr-io/ElasticsearchBundle#629]
I modified `refresh` method to look like this in 0.10 branch.

```php
    public function refresh()
    {
        $this->getClient()->indices()->refresh(['index' => $this->getIndexName()]);
    }
```

This decreased load from our ES servers about 3 times during heavy indexing and searching. Probably due to the fact, that up until now, all `_refresh` commands were performed on ALL indexes. This needs to be fixed for `_flush` probably as well.

**Comment by saimaz** [comment]
I will check it with `1.0`. That's an interesting find. Thanks for the notice. Sadly `0.10` branch is quite old and not maintainable. But if you need this functionality for your project please open a PR and I will release a patch.
