### ISSUE TITLE
Search in Index without defined Type

### ISSUE THREAD

**Issue by PatrickElsingDev** [ongr-io/ElasticsearchBundle#647]
Is it possible to search in the hole Index over all Types?

**Comment by einorler** [comment]
If you want to search over several types at once, $manager->execute() method accepts an array of types to execute the search on, so you simply need to know what types you have, or need to include in your search

**Comment by saimaz** [comment]
Hi,

here's short example how you could execute a term query on all types in the index:

```php
        $em = $this->get('es.manager.default');
        $search = new Search();
        $search->addQuery(
            new TermQuery('color', 'black')
        );
        $em->search([], $search->toArray());
```

**Comment by PatrickElsingDev** [comment]
Hi @saimaz 
Thank you very much! 
That´s it!
