### ISSUE TITLE
Suggest in results

### ISSUE THREAD

**Issue by einorler** [ongr-io/ElasticsearchBundle#662]
Currently if one is using suggesters, the only way it is possible to retrieve the desired results is:
`$result = $repo->execute($search, Result::RESULTS_RAW);`
IMO it would be nice to have the possibility to retrieve these results from `DocumentIterator`, or `RawIterator`. Does anyone have any thoughts on this?

**Comment by saimaz** [comment]
Suggest as a result already in the RAW response. There is no logic way to put them in other types of responses.
