### ISSUE TITLE
getDocumentType generates bad type name if no annotation provided

### ISSUE THREAD

**Issue by einorler** [ongr-io/ElasticsearchBundle#664]
In `DocumentParser.php` when indexing a `ParentDocument` annotation a parent type is generated from the `class` variable provided in the annotation. However, when one provides `AppBundle:ParentType` (as provided by the documentation), the `getDocumentType` method returns `ParentType` instead of `parent_type` if no type name is given in the annotation of the class. 
The problem lies here:
https://github.com/ongr-io/ElasticsearchBundle/blob/b2b18b6e15342ddb1a3fd61aa2db6a1cd8677754/Mapping/DocumentParser.php#L378
The method `$reflectionClass->getShortName()` here simply returns the name without the namespace, as given in the documentation:
http://php.net/manual/en/reflectionclass.getshortname.php

**Comment by mvar** [comment]
@einorler we don't need namespace. This is the same "caser" problem we had here: [#623](https://github.com/ongr-io/ElasticsearchBundle/issues/623#issuecomment-217884862). Looks like that issue was not properly tested after the fix was made.

**Comment by einorler** [comment]
No, it was, you're right, it was the same issue, only the fix is not merged to the master branch yet, its fixed in `1.0`

**Comment by einorler** [comment]
Duplicate of #623
