### ISSUE TITLE
Suggestion to move Repository and Manager class names to parameters

### ISSUE THREAD

**Issue by Platzengys** [ongr-io/ElasticsearchBundle#672]
Hello,

can you move hardcoded classes "ONGR\ElasticsearchBundle\Service\Repository" and "ONGR\ElasticsearchBundle\Service\Manager" in MappingPass to parameters? This will allow to extend these classes easier.

**Comment by saimaz** [comment]
Moving those classes to `MappingPass` won't make any difference. If there is any reason to extend manager simply override service name with an alias the new service will be used instead. 

btw what is the reason to extend `Manager` or `Repository`?

**Comment by Platzengys** [comment]
The reason behind that is to implement something similar to [Doctrine Filters](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/filters.html) in order to add more search parameters to every search query automatically.

**Comment by saimaz** [comment]
Very soon there should be released a new version including events which would help to make such changes. For the curiosity, you can check what's happening in master branch ;)
