### ISSUE TITLE
Associated array not working in embedded object

### ISSUE THREAD

**Issue by alexander-schranz** [ongr-io/ElasticsearchBundle#674]
Not sure if this is only because the class is also an embedded object.

```php
    /**
     * @var array[]
     *
     * @Property(type="object")
     */
    public $thumbnails = [];
```

content of thumbnails is the following:

```php
$thumbnails = [
    '500x' => '/test.jpg',
    '200x' => '/test2.jpg',
];
```

Get the following error: `Notice: Undefined index: multiple"`: @ https://github.com/ongr-io/ElasticsearchBundle/blob/v1.1.1/Result/Converter.php#L104

I'm not sure if object is the correct type for this associative array. It would work if i add the following code but I think the multiple should be set everytime?:

```php
if (!array_key_exists('multiple', $aliases[$name])) {
    return $value;
}
```

**Comment by einorler** [comment]
Hi, @alexander-schranz ,
Here I should note that there is no property type `object`, what you should use here is create a `Thumbnails` class with object notation and embed it as a separate object. Detailed explanation can be found in the docs for the mapping, under the section "Document properties annotations":
http://docs.ongr.io/ElasticsearchBundle/mapping

**Comment by saimaz** [comment]
Associated arrays have to be set as objects. Assuming that this is not the issue, otherwise please reopen.

**Comment by alexander-schranz** [comment]
@einorler @saimaz a thumbnail class would have not my expected return value it would be:

```json
{
    "thumbnails": [
         [
             "key": "50x50",
             "value": "test.jpg",
         ]
     ]
}
```

Instead of:

```json
{
    "thumbnails": [
         [
             "50x50": "test.jpg"
         ]
     ]
}
```

For me I solve it just index it as json encoded string with other name and create a `getThumbnails` function which will json decode it there.
