### ISSUE TITLE
Include metadata-provider library to determine Document-Metadata

### ISSUE THREAD

**Issue by wachterjohannes** [ongr-io/ElasticsearchBundle#681]
We at [sulu](http://sulu.io) would like to use your elastic-search abstraction for our internal search engine (https://github.com/massiveart/MassiveSearchBundle). But we have some trouble when trying to extend the metadata of a document.

Is it planned to include some Metadata-Provider architecture to provide the metadata from different Sources (xml, annotations, yml or any service). We use [jms/metadata](https://github.com/schmittjoh/metadata) in our abstraction where we have adapters for elastic and zend-lucene. This Library is quite powerful and extendible. You can provide Drivers for each format and they will be combined over the class-hirarchy.

We would need that feature because we create this document on the fly (from an xml document) or extensible doctrine-entities.

**Comment by saimaz** [comment]
Hi @wachterjohannes it's great to hear that you are planning to use elasticsearch bundle. Yes, there is a plan to support other metadata types as well. The main reason is that many of developers wants to use documents as data model structure and annotations just bother in this case. I'm looking an appropriate solution for this without losing current performance.  I will take a look at [jms/metadata](https://github.com/schmittjoh/metadata) maybe that would be a solution.

**Comment by wachterjohannes** [comment]
Thanks for fast support. We already using it in our brand-new but not released [SuluArticleBundle](https://github.com/sulu/SuluArticleBundle) where we have elastic-search are requirement. But we also have troubles there with extending the document and we have a workaround (https://github.com/sulu/SuluArticleBundle/pull/21).

If you need some help with integrating the [jms/metadata](https://github.com/schmittjoh/metadata) you can contact me. I will try to help you with my expertise.

**Comment by saimaz** [comment]
Can you tell me a small example why you need to extend some documents? Elasticsearch from the core perspective is flat and we follow this practice. That's why we do not include extending as a feature.

**Comment by chirimoya** [comment]
It's more about overriding / replacing a document which implements a specific interface and e.g. add some more application specific properties. We don't need inheritance, we need extensibility ;-)

**Comment by saimaz** [comment]
Are you still having issues with extensibility? I just want to mention that there is not forbidden to extend classes, the only requirement is to have final document version in `Document` folder, it can even be an empty class which extends something different.

I'm reviewing `jms/metadata` library and it looks quite good. But it would change a lot in the architecture and I still have some concerns about performance loss. Anyway, I will include it in 3.0 major release questions, so if it will be really good after prototyping a bit, we will include it.

**Comment by wachterjohannes** [comment]
@saimaz we have solved it in a bit a weird way as we mentioned before. but we use the `jms/metadata` on some other places where we provide extensibility and there it works like a charm (: I dont think that performance is a problem because it can cache your metadata and it wont read the metadata files each time you retrieve the metadata.

**Comment by saimaz** [comment]
@wachterjohannes Could you share the solution how you use `jms/metadata`?
