### ISSUE TITLE
Manager->commit() not working when rest.action.multi.allow_explicit_index is set to false in elasticsearch config

### ISSUE THREAD

**Issue by wasinger** [ongr-io/ElasticsearchBundle#701]
For security reasons, on our ES server the option `rest.action.multi.allow_explicit_index` is set to `false` in our elasticsearch.yml.

When trying to call `$manager->commit()` I get the following error: "explicit index in bulk is not allowed".

This means that there must be no `_index`-setting in every single dataset in the body of the bulk query, but instead the index must be specified in the URL of the bulk endpoint. (See for instance https://github.com/elastic/elasticsearch-net/issues/870)

The solution to this problem would require the following changes in class `ONGR\ElasticsearchBundle\Service\Manager`:

- in method `bulk`, remove the setting `'_index' => $this->getIndexName()`
- in method `commit`, add `$bulkQueries['index']['_index'] = $this->getIndexName()` instead

**Comment by saimaz** [comment]
Nice catch. Thanks @wasinger!
