### ISSUE TITLE
Search are done with ElasticSearch property name instead of Symfony property naming

### ISSUE THREAD

**Issue by MichaelMure** [ongr-io/ElasticsearchBundle#703]
Say I have a document in Symfony with the following property:

    /**
     * @var integer
     *
     * @ES\Property(name="uID_DOCUMENT", type="integer")
     */
    private $uidDocument;

When I want to search a document I will need to use the ElasticSearch naming `uID_DOCUMENT` instead of the Symfony naming `uidDocument`.

    $repo->findOneBy(['uID_DOCUMENT' => $uidDocument])

This means that when you don't have control over the ElasticSearch naming, it will propagate in your source code and you will need to remember this mapping when coding. This is also error prone.

When you use Doctrine, you use the name of the entity's property. When a SQL request is build, the `Column` annotation is used to translate the property name to the final name. This could also be done by ElasticSearchBundle and would feel more Symfony-ish.

Granted, I have a kinda backward use case where I'm doing search in an existing ElasticSearch index instead of pushing document from Symfony.

ElasticSearchBundle v1.2.4

**Comment by saimaz** [comment]
I'm thinking about such a feature long time ago. The main problem is performance. E.g. Doctrine provides such a functionality, but that's why it is so slow with ORM.

There is an idea to provide such a querying consistency by introducing additional cache layer with the mapper. In addition, this would allow use different mapping formats, like YAML or XML.

**Comment by MichaelMure** [comment]
Doctrine indeed does this with a huge lot of code and reflection to build metadata object. This is done again and again for each request in dev environment at least.

**Comment by saimaz** [comment]
I don't see any chance to implement such a feature.
