### ISSUE TITLE
Convenience method for retrieving existing IDs in repo, or deleting old documents

### ISSUE THREAD

**Issue by wasinger** [ongr-io/ElasticsearchBundle#708]
When updating an Elasticsearch index from the "real" data, all items that currently exist in the data source are updated or inserted correctly, but records that have been deleted in the data source are still in the Elasticsearch index.

To delete them, I usually
1. while updating, remember all existing document IDs of the data source in an array `$src_ids`
2. fetch all document IDs from the ES index/type (using a scan/scroll search with an empty fields array)
3. remove all documents from the index that are not in `$src_ids`

For step 2, I would like to have a convenience method `listAllIds()` in the `Repository` class that returns an array of all document IDs in the correspoding ES index/type.

Alternatively, there could also be a method `Repository::removeAllDocumentsExcept(array $src_ids)` that would combine step 2 and 3. Maybe that would perform better because the deletion of the documents could be performed right in every scroll step of the ID listing.

What do you think about this proposal? Or is there already another solution to this problem that I am not aware of?

**Comment by saimaz** [comment]
I might understand in a wrong way but it sounds like a specific project stuff. In terms of helpers like to get all id's, delete by query and etc.. it can be endless. What I want to say is that I don't want to make bundle fat and slow due overhead of functionality which can be achieved in a few lines of code inside the project. 

I'm a bit confused you say that after delete there are still documents in the source. What does it mean?

**Comment by saimaz** [comment]
Will be implemented in #841
