### ISSUE TITLE
document_dir is not configurable anymore

### ISSUE THREAD

**Issue by oliver-schulz** [ongr-io/ElasticsearchBundle#714]
Why was the document_dir configuration removed from config.yaml? Also it is not possible to override the DocumentFinder class, because MetadataCollector references directly to the constraint of DocumentFinder class.

I have tested to change the directory to "Entity", works great on the first view. Is it possible to bring back this feature, or do i miss something here?

**Comment by saimaz** [comment]
I'm investigating if there has any performance impact in the `prod` env. If not, then it can be returned back. Any help would be appreciated.
