### ISSUE TITLE
Memory issue when iterating

### ISSUE THREAD

**Issue by MichaelMure** [ongr-io/ElasticsearchBundle#716]
I need to iterate over the whole set of document i have:

```php
$listingRepo = $this->getContainer()->get('acme_repository.listing');
$search = $listingRepo->createSearch()->addQuery(new MatchAllQuery());
$search->setScroll();

$it = $listingRepo->findRaw($search);

foreach ($it as $raw) {
    // do stuff
}
```

If I do this, the memory usage grow until it it the configured PHP limit and the execution stop. Is there a way to allow php to reclaim the memory once the document is iterated ? With Doctrine, you can do `$em->detach($entity)` that break all the handling of this entity by Doctrine and allow php to free the memory if you don't use it elsewhere.

PHP 5.6
ElasticsearchBundle v1.2.4

**Comment by MichaelMure** [comment]
Ok after more investigation, the problem lie in Elasticsearch\Connections\Connection::tracer that is set by ElasticsearchBundle. This logger accumulate all the request/reply done and ultimately overflow the maximum memory.

If I replace this logger (by editing the source) with a NullLogger, the memory problem is gone, and it's something like 2 times faster.

Is there a way to disable this tracer more cleanly ?

**Comment by einorler** [comment]
This is a documentation page on configuration: http://docs.ongr.io/ElasticsearchBundle/configuration

The part you are interested in is the `logger` under the `managers` node. The logger is by default disabled in production and enabled in develop modes, but you can alter its behaviour with the setting above.

**Comment by saimaz** [comment]
If you dont need profiler and logger in development env you can disable them in the config. The production env is optimized a lot for performance. For example if you run any import or other cli commands with a use of elasticsearch bundle run them with `--env=prod`. Also in development env elasticsearch bundle on each query request scans document directory and collects mapping while in a prod it is cached.

**Comment by MichaelMure** [comment]
That's what I figured out. 

For the record however, only the `Connection::log` will be affected by the configuration, not `Connection::trace`.

The tracer is set in ONGRElasticsearchExtension:
```php
$definition = new Definition(
    'ONGR\ElasticsearchBundle\Service\ManagerFactory',
    [
        new Reference('es.metadata_collector'),
        new Reference('es.result_converter'),
        $container->getParameter('kernel.debug') ? new Reference('es.tracer') : null,
    ]
);
```

Thanks for the help !
