### ISSUE TITLE
parseResult in  5.*

### ISSUE THREAD

**Issue by pawelkolanowski** [ongr-io/ElasticsearchBundle#733]
$search = new Search();
        $search->addQuery(new TermQuery('title', 'foo'));

        $manager = $this->get('es.manager');
        $results = $manager->search(
            ['type_1', 'type_2'],
            $search->toArray(),
            $search->getQueryParams()
        );

````$result```` value:

    array:4 [
        "took" => 2
        "timed_out" => false
        "_shards" => array:3 []
        "hits" => array:3 [
            "total" => 2
            "max_score" => 0.6931472
            "hits" => array:2 [
                0 => array:5 [
                    "_index" => "acme"
                    "_type" => "type_1"
                    "_id" => "1"
                    "_score" => 0.6931472
                    "_source" => array:1 []
                ]
                1 => array:5 [
                   "_index" => "acme"
                   "_type" => "type_2"
                   "_id" => "1"
                   "_score" => 0.5198604
                   "_source" => array:1 []
                ]
            ]
        ]
    ]

How i can convert this to Iterator?

**Comment by pawelkolanowski** [comment]
PS. I can use things like this:

    $return = [];
    foreach ($results['hits']['hits'] as $hitRaw) {
        $return[] = $this->get('es.result_converter')->convertToDocument($hitRaw, $manager);
    }

but its ugly...

**Comment by saimaz** [comment]
You want to search through 2 elasticsearch types and get the response as iterator?

**Comment by pawelkolanowski** [comment]
Yup, check old doc's: http://docs.ongr.io/ElasticsearchBundle/search

Section: Searching in Multiple Types.

On 5.* branch both functions (public) execute and (private) parseResults doesn't exists.

**Comment by pawelkolanowski** [comment]
Solved, I found ````DocumentIterator````.
