### ISSUE TITLE
Rewrite symfony annotations.cached_reader

### ISSUE THREAD

**Issue by tadcka** [ongr-io/ElasticsearchBundle#736]
Why rewrite symfony annotations.cached_reader? 

https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Resources/config/annotations.xml#L12

1.2 version

**Comment by tadcka** [comment]
Fixed: https://github.com/ongr-io/ElasticsearchBundle/pull/737

**Comment by saimaz** [comment]
That makes sense.
