### ISSUE TITLE
Twig template error on profiler panel

### ISSUE THREAD

**Issue by xawiers** [ongr-io/ElasticsearchBundle#742]
Open profiler ongr page `app_dev.php/_profiler/abd748?panel=ongr.profiler` and get error:

An exception has been thrown during the rendering of a template ("Warning: A non-numeric value encountered").

[2/2] Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Warning: A non-numeric value encountered").   -
in vendor/ongr/elasticsearch-bundle/Resources/views/Profiler/profiler.html.twig at line 54   -

replace
```
<li class="{{ cycle(['odd', 'even'], i) }}" data-extra-info="{{ query.time }}" data-target-id="{{ i ~ q }}">
```
with
```
<li class="{{ cycle(['odd', 'even'], q) }}" data-extra-info="{{ query.time }}" data-target-id="{{ i ~ q }}">
````

    - PHP 7.1.1
    - Elasticsearch version 5.1.2
    - Bundle version 5-master

**Comment by saimaz** [comment]
Thank you @xawiers
