### ISSUE TITLE
Mapping for new type in an existing index

### ISSUE THREAD

**Issue by wachterjohannes** [ongr-io/ElasticsearchBundle#748]
A bit of context: I have added a new document-type with a mapping and want that to add to a already existing index. When i now create a new document of this type elasticsearch uses the auto detection for the mapping.

**My Conclusion:**

Please correct me if i am wrong: The mapping of the newly type will never be pushed to elasticsearch because the `ongr:es:index:create` will not be called anymore. 

Do you have any thoughts about that?

My environment: 
* PHP 7.0
* ES 2.4
* ONGR v1.2.6

**Comment by saimaz** [comment]
Yes there is no mapping update command because in the elasticsearch there is no way to do that (Exceptions [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html#updating-field-mappings)) and elasticsearch best practice is to recreate the whole index when the mapping was changed.

**Comment by saimaz** [comment]
My advice would be to use timestamped indexes with aliases.

**Comment by wachterjohannes** [comment]
but it would be possible to put a new type? maybe it would be a good DX to add a command which do that?

**Comment by saimaz** [comment]
Yes, it would. To make it like specific type a manual addition would be easy to implement. e.g. `ongr:es:index:update AppBundle:Product`.

Let's keep this issue open, and I will take a look how to add such a feature let's say in `v5.1`.

**Comment by cadavre** [comment]
Any news on this issue?

**Comment by saimaz** [comment]
This is an old issue.. At the time of writing nobody knew that elasticsearch will drop the types support. So the news is that it won't happen in any version of this bundle. The newest practise is if your mapping was changed you need to recreate the index, this is also recommended by elasticsearch guys. I'm slowly designing a v6 for this bundle where all known new features for elasticsearch will be implemented.
