### ISSUE TITLE
Plans automatic indexing ?

### ISSUE THREAD

**Issue by vamsiikrishna** [ongr-io/ElasticsearchBundle#752]
Hi,

Thanks for creating this bundle ! 
Just wanted to ask if there are any plans for integrating this bundle with Doctrine Entities and Automatic Indexing.

Also it will be useful to know how the users of this bundle are updating their Index based on CRUD operations performed using Doctrine ORM. 

Regards

**Comment by saimaz** [comment]
Yes, there are some plans. In #681 there is an idea to introduce a `metadata-provider`  library for metadata collecting. In a nutshell, you can define elasticsearch mapping by YAML files. That would allow use Doctrine entities just as it is. 

Usual practice to index data is to write a `cli` command in your project which scroll's the index and then imports via bulk all data. To track changes you can write an event listener for doctrine post-commit action and reindex single entity by its id to the elasticsearch.

**Comment by saimaz** [comment]
Will be solved by introducing _reindex endpoint support #872
