### ISSUE TITLE
How can i define character filter

### ISSUE THREAD

**Issue by wachterjohannes** [ongr-io/ElasticsearchBundle#758]
I would like to define a character filter. According to the docs - it should be possible in the analysis config:

* https://github.com/ongr-io/ElasticsearchBundle/blob/5.0/Resources/doc/mapping.md

But in your config tree it is never defined. also when i add it to the filter section the mapping which will be generated is wrong, see following snippet:

```json
analysis": {
  "filter": {
    "concat": {
      "pattern": "\\s+",
      "type": "pattern_replace",
      "replacement": ""
    }
  },
  "analyzer": {
    "folding": {
      "filter": [
        "lowercase",
        "asciifolding",
        "concat"
      ],
      "tokenizer": "nGram_tokenizer"
    }
  }
}
```

**Comment by saimaz** [comment]
@wachterjohannes which bundle version?

**Comment by wachterjohannes** [comment]
we are using v1.2.7

**Comment by PortaltechGithub** [comment]
This version does not allow char_filter. If you can, use the newest version of this bundle or you have to use the event defined in `\ONGR\ElasticsearchBundle\Service\ManagerFactory::createManager()'

Or just make a mapping update request on your own only with the `ONGR/elasticsearc-dsl`. Close index, update mapping, open index again.

**Comment by saimaz** [comment]
char filter is supported in v5
