### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by kamalkech** [ongr-io/ElasticsearchBundle#761]
Your documentation if realy to bad because is not clair enouph and many example not working, that raison i swicth to use https://github.com/elastic/elasticsearch-php and i hope your documentation will be good in the futur.

**Comment by saimaz** [comment]
Thanks for your feedback @kamalkech. Hope that docs are now much better. I'm closing this issue, and it doesn't mean we will stop adding info to the docs :). It will be continuous work.
