### ISSUE TITLE
findByIds - Undefined index: hits

### ISSUE THREAD

**Issue by arjanfrans** [ongr-io/ElasticsearchBundle#766]
When using `findByIds` I get an exception when there are no hits. ` Notice: Undefined index: hits`

By looking at the code `ongr\elasticsearch-bundle\Service\Repository.php line 119` it looks that `hits` is not defined on the `$return`. A simple fix would be to initialize it with `hits` and `total` with default values ([] and 0).

PHP version: 7.0.16
Elasticsearch version: 2.4.4
Bundle version: 1.2.7

**Comment by einorler** [comment]
Hey @arjanfrans,
Good catch, I'll take care of it straight away
