### ISSUE TITLE
Parent Mapping does not work

### ISSUE THREAD

**Issue by PortaltechGithub** [ongr-io/ElasticsearchBundle#772]
I tried to map a parent document via annotation. I debugged some code and can't find the spot where `_parrent` is mapped to index. My configuration from the property is stored in aliases, but then the journey ends :)

In `\ONGR\ElasticsearchBundle\Mapping\DocumentParser::getAliases()`  calls `$this->getMetaFieldAnnotationData($property)`. The correct parent type appears in `settings`, but this informations is not further used.

Also in \ONGR\ElasticsearchBundle\Mapping\MetadataCollector::getClientMapping the config will be cropped from the $mapping.

I think this function is totaly broken, but i can't find the right spot to provide a bugfix.

**Comment by PortaltechGithub** [comment]
I investigated some more time in this topic, i think its more complicated as just setting the parent value. You need to store all parents and children in the same shard. So also the routing feature is missing here i think.

https://www.elastic.co/guide/en/elasticsearch/guide/current/indexing-parent-child.html

**Comment by saimaz** [comment]
I will check this, thanks for the issue @PortaltechGithub.

**Comment by toooni** [comment]
@PortaltechGithub are you sure? IMO setting the parent property should do the job. Keeping the parents and children in the same shard is the job of elasticsearch. I might be wrong as I am still trying to wrap my head around elasticsearch.. 
> This parent ID serves two purposes: it creates the link between the parent and the child, and it ensures that the child document is stored on the same shard as the parent.

**Comment by oliver-schulz** [comment]
@toooni in my case i can add and remove related objects via GUI, so i have to take care about routing first, because id don't know in witch shard the related doc sits. 

My workaround was to handle relations on application site, this is also a suggested solution by elastic.

After a while working with ES, you painfully recognize, elasticsearch is only good for super fast prefix and match queries ;)

**Comment by saimaz** [comment]
Seems related to #803

**Comment by saimaz** [comment]
Will be fixed in #803 and V6 by introducing `join` type support
