### ISSUE TITLE
Support Common Collections?

### ISSUE THREAD

**Issue by mcrumm** [ongr-io/ElasticsearchBundle#774]
Would you be open to a PR that replaced the custom `ONGR\ElasticsearchBundle\Collection\Collection` with an implementation from [doctrine/collections](https://github.com/doctrine/collections)?

Defining objects that might share common functionality between an ORM layer and ElasticsearchBundle gets far more difficult when the two can't utilize a common Collection interface, since objects getting collections from ElasticsearchBundle have to be of ONGR's custom type.

I have an implementation based around using `ArrayCollection` that passes all of the current tests on the `5.0` and `5.1-dev` branch.  I'd be happy to submit a PR if you're interested.

**Comment by saimaz** [comment]
Sure I'm interested. I'm thinking about `doctrine/collections` quite a while. Sadly didn't have enough time to implement it yet.
