### ISSUE TITLE
Generating document adds a type on object annotation  

### ISSUE THREAD

**Issue by fattouchsquall** [ongr-io/ElasticsearchBundle#779]
The problem is that the generate of document add a type for annotation of type object if the name of the class is in camelcase and the collection's name is underscored.

`
$this->generateService->generate(
                $bundle,
                'VideoFormat',
                'object',
                'video_format',
                [['annotation': 'property', 'property_name': 'test', 'field_name': 'test', 'property_type': 'text']]
            );
`

My PR to fix this behavior: https://github.com/ongr-io/ElasticsearchBundle/pull/778

**Comment by saimaz** [comment]
Solved in #782
