### ISSUE TITLE
Deprecated warning in execute function (v1.x.x)

### ISSUE THREAD

**Issue by shine60vn** [ongr-io/ElasticsearchBundle#785]
Hi,
The `execute` function of `Repository` class is marked as `@deprecated`. It suggests using strict execute functions instead. e.g. `executeIterator`, `executeRawIterator`. But I could not find both of them in the latest release (v1.2.9). I also see the `execute` is renamed to `executeSearch` since v5.x.x.
The deprecated warning does not block my work but it's so annoying. Any suggestion to get rid of those warnings?
Thanks!

**Comment by saimaz** [comment]
Hi @shine60vn, this is a good notice. It definitely has to be added.

**Comment by shine60vn** [comment]
Thanks, @saimaz. Would you please add them in next patch?

**Comment by shine60vn** [comment]
Hey @saimaz , any update on this?

**Comment by saimaz** [comment]
This one is so old, I hope you are not using v1 anymore.
