### ISSUE TITLE
execute($search) function raises error in 5.x

### ISSUE THREAD

**Issue by dijadev** [ongr-io/ElasticsearchBundle#795]
Hi!
I've upgraded my bundle to 5.0.0 version and noticed that the function execute of the Repository service  class "ongr-io/ElasticsearchBundle/blob/master/Service/Repository.php" is not working, But replacing it with findDocuments($search) works.
This should be mentionned in the releases.

Thank you.

**Comment by saimaz** [comment]
Well, I'm sure it was mentioned in breaking change release note. But thanks for the notice, will make sure next time release notes are more clear.
