### ISSUE TITLE
Working with aliases and ONGR

### ISSUE THREAD

**Issue by oliver-schulz** [ongr-io/ElasticsearchBundle#796]
In ES you typical use only aliases to communicate with your indexes, because you have allways background tasks to index data and so on. With the aliases you can switch to a new index without downtime.

I have a simple setup:
'docs1' and 'docs2' with alias 'docs'.
How can i configure ONGR bundle to use only the alias, instead of the the index name?

I have seen the create command has some alias feature, but this seems to be useless at all?

I would suggest to add some kind of index switch command, witch cycles through configured aliases or some kind?

Any ideas oder plans to integrate such feature?

**Comment by saimaz** [comment]
You can create a new index (with alias) using `ongr:es:index:create -a -t` command. It will use index name from config for alias name. The real index names will be timestamped. 

Hope it could solve your concern.

**Comment by oliver-schulz** [comment]
Yeah, i have seen this features, but this works not in my case.

I solved it by implementing my own commands:
**index:initalize**
creates two indicies: `$manager->getIndexName .'-' . date(dmyhis)`
Index one gets an alias on $manager->getIndexName()
Index two gets an alias on  $manager->getIndexName() . '_reindex'

in my elastic search config i added one more manager 'docs_reindex'.

**index:switch**
iterates through the index names and aliases and switches the alias from $manager->getIndexName() . '_reindex' to $manager->getIndexName()

**index:reindex**
drops the previous `reindex` index and creates a new index with a fresh mapping 

With this setup you can easily switch between a new an an old index without any downtime. The create command does not work in my case, because i cant switch back also i cant really identify the indicies later in my code (also the dots in the date are looking wrong)

**Comment by saimaz** [comment]
Reindex API is planned to add in v6
