### ISSUE TITLE
Inner hits with _source

### ISSUE THREAD

**Issue by demianchuk** [ongr-io/ElasticsearchBundle#809]
Hi

How can I build next query using ONGR:

{
    "has_parent": {
          "parent_type": "user_document",
          "query": {
                 "match_all": []
            },
             "inner_hits":{
                  "_source" : ["awards"]
             }
      }
  }

**Comment by saimaz** [comment]
This is an old question, but guys, can you please ask those question in the StackOverflow and use `ongr` tag.
