### ISSUE TITLE
Bundle doesn't work with Symfony Flex

### ISSUE THREAD

**Issue by starspire** [ongr-io/ElasticsearchBundle#814]
Hi,
From Symfony version 3.3 there is new way of building Symfony apps -> Symfony Flex, which replaces standard Symfony Installer. Along with the new tool Symfony also breaks symfony/symfony package to over a dozen standalone components and restrict longer uses symfony/symfony. Because of requiring in composer this package I cannot install bundle with application using new build system. To fix that you should require in composer.json only symfony components the bundle depends on, not whole symfony/symfony package.

    - PHP 7.1.8
    - ES 5.6
    - Ongr 5.0

**Comment by saimaz** [comment]
Fixed in 5.0.4
