### ISSUE TITLE
Document-level read/write index assignment

### ISSUE THREAD

**Issue by etki** [ongr-io/ElasticsearchBundle#820]
Hi!

I just met this bundle, so i may miss something. As far as i've understood, mapping annotations can only specify which type document should be written to, which is somewhat confusing. It is planned to [deprecate types at all in ES 6.0](https://www.elastic.co/guide/en/elasticsearch/reference/master/removal-of-types.html), and the whole world moves toward to index-based document separation (i.e. all documents in index belong to same type). Current configuration implies creating separate manager for every document type, while i think indexes should belong to `@Document` annotation. It is true that single application may talk to different clusters and thus have several managers, but, i believe, each manager should work on cluster level rather than index level.

Moreover, it is quite common to use specific aliasing techniques so the application would read and write into different indexes. The most common case would be live migration - when the mapping has changed, application should simultaneously write to [old index, new index] while querying old index only - and after background reindex process has migrated all data from old index to new index switch query alias to new index. 

Because all of that, i think, documents should explicitly declare two target indexes in annotation - read-side and write-side.

**Comment by saimaz** [comment]
Thank you for the feedback @etki. The current bundle version is not designed for the Eelasticsaerch 6.0, but I for sure will release support for this in the future.

For your further concerns due `Document` we all have been thinking about those issues, from one perspective it sounds easy, but it is complicated to implement and support all the cases. If you have anything in mind how it can be realized you are more than welcome to open a PR or create a more detailed issue with the specific ideas.
