### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by alexander-schranz** [ongr-io/ElasticsearchBundle#832]
First I want to say the bundle is a good work and helped us alot but asking myself if this project is still maintained?

We build several projects based on this bundle. At current state we implement some forks which works for us for example the #803 issue. But we also have problems currently with the php 7.2 support and some people ask for the ES 6 support in our projects (#828). Is this project planning to support this or is this project not longer maintained? What are the current problems? Where can we help? Are you willing to give merge permissions to someone else?

**Comment by trickreich** [comment]
Maybe you can give use some feedback here? Thanks!

**Comment by alexander-schranz** [comment]
Would be awesome if some of @nfq-extremes, @nfqde or @nfqakademija could give us any feedback:

/cc @saimaz @chyzas @ellisv @entregrammer @murnieza @tautrimas @emaslak @GrandLTU @gytislakavicius @Im0rtality @murnieza @mvar @riddl @Zylius @ellisv @pjarmalavicius 

Sorry to mention you all but the ONGR mail server seems also be offline.

**Comment by saimaz** [comment]
Hey there guys, first of all, I'm very sorry for the late response. The short answer is yes this bundle and most of the others in this organization are alive :). There will be support for ES 6 and PHP 7.2 because I need these things in my upcoming projects as well as many others in the community. It's not very easy to introduce all major versions of ONGR bundles quickly due to some critical changes in the ES6. I have some ideas how to do this and will release elasticsearch-dsl beta to let some others try it as well.

**Comment by alexander-schranz** [comment]
@saimaz Good to here from you and thank you for your response. Can we help in any way? We had also some open issues with current version were PRs are open which would fix it for us example #817 but nobody seems to review this PRs. Are there any other maintainers then you. You normally don't investigate time to create a PRs for a project where the maintainers seem not review them or give any feedback

What is your current roadmap? PHP7.2 only for 6.0 branch with ES6 only?

**Comment by saimaz** [comment]
For the 6.0 branch, I think I'll drop PHP 5.* and leave ^7.0. 7.2 is just released. But of course, the base will be tested in 7.0, 7.1 and 7.2 and upcoming PHP versions.

Regarding PRs, I'm looking at #803 and #817 why embedded fields cause the problems.

>Are there any other maintainers then you?
There are 3 of us who could review and merge. Last half year was extremely difficult for us to work on this project, but now things are much better and I believe we will rise this up ;)
