### ISSUE TITLE
v5.0.5 deprication in Symfony v3.4.4

### ISSUE THREAD

**Issue by JanisGruzis** [ongr-io/ElasticsearchBundle#833]
Hi. I have issue with deprecation in this bundle combined with Symfony 3.4.4. Version

```
composer info | grep ongr
ongr/elasticsearch-bundle            v5.0.5              Elasticsearch bundle for Symfony.
```

error I face

```
8x: The "es.manager.default" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.
```

**Comment by saimaz** [comment]
It's deprecated because it won't be supported in Symfony 4. In this bundle next major version (which will support Symfony 4) I will inject repositories directly into auto wiring container. There won't be any more any service names like now.
