### ISSUE TITLE
Symfony4 and ES6  / ETA

### ISSUE THREAD

**Issue by helmuthva** [ongr-io/ElasticsearchBundle#849]
Hi,

we are currently deciding if we should go for Elastica or ongr-io/Elasticsearch-Bundle for our PHP7.2+Sf4.x services that need to access Elasticsearch 6.x

=> What is the expected time of arrival for version 6.0 of ongr-io/Elasticsearch-Bundle  supporting PHP7.2,  Sf4.x and ES 6.x?

Best

**Comment by TomKeur** [comment]
Don't use this package since it's never updated.

**Comment by saimaz** [comment]
v5.2.4 supports ES6 and Symfony 4, I also created a [v6 beta](https://github.com/ongr-io/ElasticsearchBundle/releases/tag/v6.0.0-beta) which will support ES6 and upcoming versions with planned ES breaking changes.

**Comment by dramentol** [comment]
Please,
how do you configure mapping option and how do you generate Documents with the provided command without Bundles in Symfony 4?
