### ISSUE TITLE
Can't set property option "enabled"="false"

### ISSUE THREAD

**Issue by a1ku** [ongr-io/ElasticsearchBundle#851]
Hello,

I need to have a property of my document that will not be analyzed. From my understanding this is determined by `enabled` option on property mapping definition (https://www.elastic.co/guide/en/elasticsearch/reference/5.6/enabled.html).

```php
<?php

namespace CoreBundle\Document;

use ONGR\ElasticsearchBundle\Annotation as ES;

/**
 * @ES\Document()
 *
 */
class EsActivity
{
    /**
     * @ES\Id()
     */
    protected $esId;

    /**
     * [latitude, longitude, altitude, timestamp]
     *
     * @ES\Property(type="text", options={"enabled":"false"})
     */
    protected $path;

    /**
     * @return mixed
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * @param mixed $path
     * @return EsActivity
     */
    public function setPath($path): EsActivity
    {
        $this->path = $path;

        return $this;
    }
}
```

For configuration above I keep getting index creating error:
```
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Mapping definition for [path] has unsupported parameters:  [enabled : false]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [es_activity]: M
  apping definition for [path] has unsupported parameters:  [enabled : false]","caused_by":{"type":"mapper_parsing_exception","reason":"Mapping definition for [path] has unsupported parameters:  [enabled : false]"}},"status":400}
```

I also tried:
```
@ES\Property(type="text", options={"enabled":false})
@ES\Property(type="text", options={"enable":"false"})
@ES\Property(type="text", options={"enable":false})
```
With no luck despite http://docs.ongr.io/ElasticsearchBundle/mapping stating that

> To add a custom setting for the property like analyzer include it in the options variable

Is setting `enabled` even available or maybe I misunderstood the docs?

My env:
    - PHP 7.1
    - Elasticsearch docker.elastic.co/elasticsearch/elasticsearch:5.6.11
    - ongr/elasticsearch-bundle: 5.0.7

**Comment by saimaz** [comment]
It should be `@ES\Property(type="text", options={"enabled"=false})`

`  = ` instead of the `  :  `
