### ISSUE TITLE
References to  @ES\Object are not all updated to  @ES\ObjectType

### ISSUE THREAD

**Issue by grantbriston** [ongr-io/ElasticsearchBundle#854]
Currently there are still outstanding references to the outdated version of the object annotation ( @ES\Object vs  @ES\ObjectType) namely:

1. Tests/app/fixture/TestBundle/Document/CategoryObject.php
2. Tests/app/fixture/TestBundle/Document/SubcategoryObject.php
3. Tests/app/fixture/TestBundle/Entity/CategoryObject.php

**Comment by YetiCGN** [comment]
You know, the great thing about Open Source is, you can fix it yourself and submit a pull request! 🙂

**Comment by saimaz** [comment]
It is already fixed in V6, sorry won't fix it in the v5 unless someone will open a PR ;)
