### ISSUE TITLE
Question about completion suggestor

### ISSUE THREAD

**Issue by demianchuk** [ongr-io/ElasticsearchBundle#870]
Hi
Annotation Property has type completion. And in document it would be like:
/**
    *@ES\Document(type="auction_document")
 */
class Document
{
/**
    * @ES\Property(name="city", type="completion")
    */
    public $city;
}

To index it we use:
$document = new Document();
$document->setCity('Some value');

But while indexing I need to add weight parameter also
Like in elastic documetation:
PUT music/song/1?refresh
{
    "suggest" : {
        "input": [ "Nevermind", "Nirvana" ],
        "weight" : 34
    }
}

Question is: how to add weight value using object oriented style? Is it possible?

**Comment by saimaz** [comment]
Not really at the moment, but thanks for that kind of issue. I'm currently working on a v6 major version and will take a look at how to make this possible in an objective way. 

Until then, you might try to use `options` parameter in the `Property` annotation. The other way is to modify the bulk request body by creating your own event listener and catch [PRE_COMMIT_EVENT](https://github.com/ongr-io/ElasticsearchBundle/blob/master/Event/Events.php#L27).

**Comment by demianchuk** [comment]
ok, thanks
