### ISSUE TITLE
Migration class does not exists

### ISSUE THREAD

**Issue by floriansemm** [ongr-io/ElasticsearchBundle#874]
The command `composer require ongr/elasticsearch-bundle "~6.0"` fails with the following error:

```
Updating the "config/parameters.yaml" file
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  
!!  In DocumentParser.php line 85:
!!                                                                       
!!    Class Application\Migrations\Version20180530080803 does not exist  
!!                                                                       
!!  
!!  

Installation failed, reverting ./composer.json to its original content.
```

Symfony-version: 4.1
PHP-version: 7.2

**Comment by saimaz** [comment]
v6 is not released yet. Only the beta is available at the moment of writing.

**Comment by nibsirahsieu** [comment]
Hi @saimaz , i'm trying to install the beta version (`composer require ongr/elasticsearch-bundle v6.0.0-beta2 -vvv --prefer-dist`), but always fails with message `Class DoctrineMigrations\Version20190705092420 does not exist`. How to install the bundle correctly?. Thanks in advance

**Comment by saimaz** [comment]
There is nothing related in the bundle with `DoctrineMigrations` or `DoctrineMigrations\Version20190705092420`. Please check if you have such a class which is declared at someplace in your code.

**Comment by nibsirahsieu** [comment]
The error similar as reported as by @floriansemm,

```
Executed script cache:clear  [KO]
 [KO]
Script cache:clear returned with error code 255
!!
!!  In DocumentParser.php line 85:
!!
!!    Class DoctrineMigrations\Version20190705092420 does not exist
!!
!!
!!
Script @auto-scripts was called via post-update-cmd

Installation failed, reverting ./composer.json to its original content. 
```
I'm using symfony 4.3

**Comment by saimaz** [comment]
But there is no `DoctrineMigrations` at all in the whole bundle. Can you try a hard reset of the cache by `rm -rf var/cache/*`?

The only possible problem I can imagine is that `DoctrineMigrations` folder is treated as a Documents location or smth, but for this, you need to check config and make sure there is no usage of `DoctrineMigrations` in your `Document` classes. 

Other than that there is no way I could help with this little of info :(

**Comment by ip512** [comment]
Version 6.0 is released now, but I still have this issue. Does someone know how to fix it ?

**Comment by ip512** [comment]
Finally, adding these lines to config fixed the exception: 
```
ongr_elasticsearch:
    source_directories:
        - src/App/Document
```
