### ISSUE TITLE
Add possibility to specify format for date type fields

### ISSUE THREAD

**Issue by murnieza** [ongr-io/ElasticsearchBundle#90]
Currently it is not possible to define custom format for date type fields:

`@ES\Property(name="dateField", type="date", format="YYYY-MM-dd h:i:s")`

**Comment by murnieza** [comment]
I will take a look at it again.

**Comment by saimaz** [comment]
To create document you have to pass `\DateTime` object and in the response you will get the same. It's up to you what format you will use.

**Comment by saimaz** [comment]
Unless you want to have specific date format in elasticsearch (e.g. for kibana). But I think so that elasticsearch is capable to handle various formats (e.g. timestamp and date fields). 

If not, please reopen the issue and we will solve the problem.
