### ISSUE TITLE
ES7 support

### ISSUE THREAD

**Issue by romainjanvier** [ongr-io/ElasticsearchBundle#907]
Hello,

Is the support of the Elasticsearch 7 planned ?

I got this error when my ES is in version 7.5.1 with this bundle on master branch :
```
The mapping definition cannot be nested under a type [_doc] unless include_type_name is set to   
  true.
```

Thanks for your work on this great bundle.
Romain

**Comment by saimaz** [comment]
Just released a couple of days ago. Check the releases, there is a new v7 version.
