### ISSUE TITLE
Repository::RESULTS_ARRAY does not return all fields

### ISSUE THREAD

**Issue by mindaugasbarysas** [ongr-io/ElasticsearchBundle#91]
$repository->execute($search, Repository::RESULTS_ARRAY) returns:
```
Array
(
    [0] => Array
        (
            [title] => test_prod2
            [description] => test_desc2
            [price] => 7.79
        )

    [1] => Array
        (
            [title] => test_prod
            [description] => test_desc
            [price] => 0.99
        )
)
```
There are some fields missing, particularly `id` and `score`. Is this by design?

**Comment by saimaz** [comment]
Correction. `RESULTS_ARRAY`, does not return iterator. it parses returned information from _source fields. And returns normalised array. To get full info about response in array you need `RESULTS_RAW`.
