### ISSUE TITLE
Class 'Elasticsearch\ClientBuilder' not found

### ISSUE THREAD

**Issue by pety-dc** [ongr-io/ElasticsearchBundle#912]
I use Pimcore and FrontStore which uses elasticsearch bundle, which uses elasticsearch DSL

Last time when I updated the composer.json, it updated the elasticsearch bundle to v5.2.5, which allowed the use of elasticsearch DSL 6.x

Apparently elasticsearch bundle v5.2.5 does not specifiy `elasticsearch/elasticsearch` in the require section. Elasticsearch bundle v6.0+ does

On the other hand elasticsearch DSL 5.x specifies `elasticsearch/elasticsearch` in the require section, but elasticsearch DSL 6.x does not.

Ultimately I'm left without requiring `elasticsearch/elasticsearch` because neither elasticsearch bundle v5.2.5 nor elasticsearch DSL 6.x does so. This leads to `Class 'Elasticsearch\ClientBuilder' not found` error

**Comment by saimaz** [comment]
that was a problem due dsl library missed support for a serializer 5.0, fixed in the new release
