### ISSUE TITLE
I cant see manager in ElasticsearchBundle ~7.0?

### ISSUE THREAD

**Issue by patie** [ongr-io/ElasticsearchBundle#916]
Hi,

what i can inject in ElasticsearchBundle 7.0 please? I cant see any service or class like a manager. There is also no `getRepository` method like in documentation.

thanks!

**Comment by toooni** [comment]
I've sent you a message on symfony slack.

**Comment by ilithium** [comment]
Could you also share this here please? 

I'm looking to import a large number of text files and need to parsed and converted to Document objects pre-import. It appears this is missing from the documentation so some guidance would be appreciated.

**Comment by toooni** [comment]
The docs are not up2date. The new version of this bundle does not have a manager which returns the repositories by `getRepository()`. Instead every document represents an index itself and it's service is accessible with the FQDN as the service name.

**Comment by kstanelis** [comment]
@toooni Could you give a short example of how to get it as the service? I haven't used anything like this and can't seem to grasp the concept of it.

**Comment by toooni** [comment]
@kstanelis I recommend you use the fork here https://github.com/handcraftedinthealps/ElasticsearchBundle which is based on version 5.x of this bundle but works with Elasticsearch 6 and 7 and also on Symfony 5+.

If you really want to use the ongr bundle (which seems to be more or less abandoned) you can make it work with autowiring like this:

services.yaml
```
services:
  _defaults:
    bind:
      ONGR\ElasticsearchBundle\Service\IndexService $productIndexService: '@App\Document\Product'
```

YourService.php
```
<?php

namespace App\Service;

use ONGR\ElasticsearchBundle\Service\IndexService;
...

class YourService {

    private IndexService $productIndexService;

    public function __construct(
        IndexService $productIndexService
    ) {
        $this->productIndexService = $productIndexService;
    }

    public function yourSearchFunction() : DocumentIterator {
        $search = $this->productIndexService->createSearch();

        $boolQuery = new BoolQuery();

        ...

        $search->addQuery($boolQuery);
        return $this->productIndexService->findDocuments($search);
    }
}
```

I hope this helps.
