### ISSUE TITLE
Symfony serializer dependency

### ISSUE THREAD

**Issue by patie** [ongr-io/ElasticsearchBundle#918]
There is symfony serializer composer dependency, but in code there is no real serializer usage, or im missing someting? objects and arrays are converted with custom code, is there any reason for this? symfony serializer have groups which can be much more flexible in many cases, so i suggest switch custom converter for symfony serializer or remove symfony serializer dependency

**Comment by toooni** [comment]
I think symfony/serializer was replaced in 6.2 because it wasn't the best match for the libarary.

**Comment by saimaz** [comment]
elasticsearch dsl uses serializer, so this was kind'a an inherited dependency, wil lremove in the future versions.
