### ISSUE TITLE
Symfony 5 Support

### ISSUE THREAD

**Issue by petrmalina** [ongr-io/ElasticsearchBundle#919]
Unable to install with Symfony 5 because ElasticsearchDSL requires symfony/serializer ^3.0|^4.0.

`
composer require ongr/elasticsearch-bundle
Using version ^7.0 for ongr/elasticsearch-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.0.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - ongr/elasticsearch-bundle 7.0.x-dev requires ongr/elasticsearch-dsl ^7.0 -> satisfiable by ongr/elasticsearch-dsl[7.x-dev, 7.0.x-dev, v7.0.0, v7.1.0].
    - ongr/elasticsearch-bundle 7.0.x-dev requires ongr/elasticsearch-dsl ^7.0 -> satisfiable by ongr/elasticsearch-dsl[7.x-dev, 7.0.x-dev, v7.0.0, v7.1.0].
    - ongr/elasticsearch-bundle v7.0.0 requires ongr/elasticsearch-dsl ^7.0 -> satisfiable by ongr/elasticsearch-dsl[7.x-dev, 7.0.x-dev, v7.0.0, v7.1.0].
    - ongr/elasticsearch-bundle v7.0.1 requires ongr/elasticsearch-dsl ^7.0 -> satisfiable by ongr/elasticsearch-dsl[7.x-dev, 7.0.x-dev, v7.0.0, v7.1.0].
    - ongr/elasticsearch-dsl v7.1.0 requires symfony/serializer ^3.0|^4.0 -> no matching package found.
    - ongr/elasticsearch-dsl v7.0.0 requires symfony/serializer ^3.0|^4.0 -> no matching package found.
    - ongr/elasticsearch-dsl 7.0.x-dev requires symfony/serializer ^3.0|^4.0 -> no matching package found.
    - ongr/elasticsearch-dsl 7.x-dev requires symfony/serializer ^3.0|^4.0 -> no matching package found.
    - Installation request for ongr/elasticsearch-bundle ^7.0 -> satisfiable by ongr/elasticsearch-bundle[7.0.x-dev, v7.0.0, v7.0.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
`

**Comment by saimaz** [comment]
fixed in the elasticsearch dsl
