### ISSUE TITLE
Timestampable and Sluggable extensions

### ISSUE THREAD

**Issue by trylika** [ongr-io/ElasticsearchBundle#92]
There are some documents, which need fields like createdAt or updatedAt. There are useful extensions for doctrine, which we could remake for ESB and use:

https://github.com/l3pp4rd/DoctrineExtensions/blob/master/doc/timestampable.md

https://github.com/l3pp4rd/DoctrineExtensions/blob/master/doc/sluggable.md

**Comment by tautrimas** [comment]
@saimaz, have you discussed this?

**Comment by saimaz** [comment]
Yes we did but it's still in the discussion.

**Comment by martiis** [comment]
We should support at least prePersist and preUpdate methods in upcoming weeks, but annotation shortcuts like that in near future I guess :)

**Comment by saimaz** [comment]
+1 for Timestampable

Sluggable we can handle via `pre` events, IMO no need some special annotation. We can investigate this again, but not sure it is necessary.

**Comment by saimaz** [comment]
I think we can introduce here `TimestampableAwareTrait`. There are already some repositories where we need timestamps.

**Comment by trylika** [comment]
but why with trait? Can't we implement annotation style functionality as was done in DoctrineExtensions? it would be much more versatile and end-user could configure which events he wants and in which fields should they be stored.

**Comment by saimaz** [comment]
1st point is to let extend it if necessary. 
2nd with trait you do not need to define anything, its easier to collect instead of annotation. 

p.s. DoctrineExtensions also has `Timestampable` trait ;).

**Comment by trylika** [comment]
yeah, we could have both :) Trait is usefull as is annotations, but in different situations.

**Comment by saimaz** [comment]
Solved in #405 

Was added `Timestampable` trait
